'use client';
import {useEffect,useRef,useState} from 'react';
import {Camera,Check,ImagePlus,LoaderCircle,LockKeyhole,Trash2,X} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Slider} from '@/components/ui/slider';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {BODY_FIELDS,cloneBody,setMeasurement,validateBody,makePreset,sourceLabel} from '@/lib/wardrobe/body';
import type {BodyKey,BodyProfile} from '@/lib/wardrobe/types';

type PhotoFile={file:File;url:string};
export default function BodyEditor({open,onOpenChange,body,onSave,onDelete}:{open:boolean;onOpenChange:(o:boolean)=>void;body:BodyProfile;onSave:(b:BodyProfile)=>void;onDelete:()=>void}){
 const [draft,setDraft]=useState(()=>cloneBody(body)),[tab,setTab]=useState('simple'),[shape,setShape]=useState<'slim'|'regular'|'broad'>('regular');
 const [photos,setPhotos]=useState<Partial<Record<'front'|'side',PhotoFile>>>({}),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState(''),[result,setResult]=useState(false),[reviewed,setReviewed]=useState(false),[preserved,setPreserved]=useState<string[]>([]);
 const worker=useRef<Worker|null>(null),timeout=useRef<ReturnType<typeof setTimeout>|null>(null),filesRef=useRef(photos),generation=useRef(0);filesRef.current=photos;
 function stop(){generation.current++;worker.current?.terminate();worker.current=null;if(timeout.current)clearTimeout(timeout.current);timeout.current=null;}
 useEffect(()=>{if(open){setDraft(cloneBody(body));setError('');setResult(false);setReviewed(false);setTab('simple');}else{stop();Object.values(filesRef.current).forEach(p=>URL.revokeObjectURL(p.url));setPhotos({});setBusy(false);}},[open,body]);
 useEffect(()=>()=>{stop();Object.values(filesRef.current).forEach(p=>URL.revokeObjectURL(p.url));},[]);
 function change(key:BodyKey,n:number){setDraft(b=>setMeasurement(b,key,n,'manual'));setReviewed(false);}
 function fileChange(kind:'front'|'side',file?:File){if(!file)return;setError('');setResult(false);setReviewed(false);if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('JPG, PNG, WebP 사진을 선택해 주세요.');return;}if(file.size>15*1024*1024){setError('사진 한 장의 크기를 15MB 이하로 줄여 주세요.');return;}if(photos[kind])URL.revokeObjectURL(photos[kind]!.url);setPhotos(p=>({...p,[kind]:{file,url:URL.createObjectURL(file)}}));}
 async function analyze(){if(!photos.front||!photos.side||busy)return;setError('');setResult(false);setReviewed(false);setBusy(true);setProgress('사진을 준비하고 있어요…');stop();const run=generation.current;let front:ImageBitmap|undefined,side:ImageBitmap|undefined;
  try{if(!('Worker'in window)||!('OffscreenCanvas'in window))throw new Error('이 브라우저는 기기 내 사진 분석을 지원하지 않아요. 상세 치수 입력을 이용해 주세요.');
   front=await createImageBitmap(photos.front.file);side=await createImageBitmap(photos.side.file);if(generation.current!==run){front.close();side.close();return;}
   if(front.height<360||side.height<360)throw new Error('세로 360픽셀 이상의 선명한 전신사진을 사용해 주세요.');
   const w=new Worker(new URL('../lib/wardrobe/photo-worker.ts',import.meta.url),{type:'module'});worker.current=w;
   const finish=()=>{w.terminate();worker.current=null;if(timeout.current)clearTimeout(timeout.current);setBusy(false);};
   w.onmessage=e=>{if(generation.current!==run)return;if(e.data.type==='progress'){setProgress(e.data.message);return;}if(e.data.type==='result'){if(!validateBody(e.data.body)){setError('추정치가 지원 범위를 벗어났어요. 상세 치수를 입력해 주세요.');finish();return;}setDraft(e.data.body);setPreserved((e.data.preserved as BodyKey[]).map(k=>BODY_FIELDS.find(f=>f.key===k)!.label));setResult(true);setProgress('');finish();}else if(e.data.type==='error'){setError(/[가-힣]/.test(e.data.message)?e.data.message:'사진 분석 도구를 실행하지 못했어요. 다시 시도하거나 상세 치수를 입력해 주세요.');finish();}};
   w.onerror=()=>{if(generation.current===run){setError('분석 도구를 불러오지 못했어요. 다시 시도하거나 상세 치수를 입력해 주세요.');finish();}};
   timeout.current=setTimeout(()=>{if(generation.current===run){setError('분석 시간이 길어지고 있어 중단했어요. 다시 시도하거나 상세 치수를 입력해 주세요.');finish();}},90000);
   w.postMessage({front,side,height:draft.measurements.height,body:draft,origin:window.location.origin},[front,side]);
  }catch(e){front?.close();side?.close();setError(e instanceof Error?e.message:'사진을 읽지 못했어요. 파일 형식을 확인해 주세요.');setBusy(false);}
 }
 const valid=validateBody(draft);const canSave=valid&&!busy&&(!result||reviewed)&&(tab!=='photo'||result);
 const fields=(sliders:boolean)=>BODY_FIELDS.filter(f=>!sliders||f.key!=='head').map(f=><div className="body-field" key={f.key}><label htmlFor={`body-${f.key}`}><span>{f.label}<small className="field-source">{sourceLabel[draft.sources[f.key]]}</small></span><span className="number-with-unit"><Input id={`body-${f.key}`} type="number" inputMode="decimal" min={f.min} max={f.max} step="0.5" value={Number.isFinite(draft.measurements[f.key])?draft.measurements[f.key]:''} aria-invalid={!Number.isFinite(draft.measurements[f.key])||draft.measurements[f.key]<f.min||draft.measurements[f.key]>f.max} onChange={e=>change(f.key,e.target.value===''?NaN:Number(e.target.value))} disabled={busy}/>cm</span></label>{sliders&&<Slider min={f.min} max={f.max} step={.5} value={[Number.isFinite(draft.measurements[f.key])?draft.measurements[f.key]:f.min]} onValueChange={([v])=>change(f.key,v)} aria-label={f.label} disabled={busy}/>}<p>{f.hint} · {f.min}–{f.max}cm</p></div>);
 return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent className="body-editor"><SheetHeader><span className="eyebrow">MY BODY PROFILE</span><SheetTitle>나의 체형 설정</SheetTitle><SheetDescription>내 치수를 반영해 더 가까운 실루엣으로 살펴보세요.</SheetDescription></SheetHeader>
 <Tabs value={tab} onValueChange={v=>{if(!busy)setTab(v);}} className="editor-tabs"><TabsList className="editor-tab-list"><TabsTrigger value="simple" disabled={busy}>간편 설정</TabsTrigger><TabsTrigger value="manual" disabled={busy}>상세 치수</TabsTrigger><TabsTrigger value="photo" disabled={busy}>사진 추정</TabsTrigger></TabsList><div className="editor-scroll">
 <TabsContent value="simple"><div className="editor-section-label">기본 체형으로 시작하기</div><div className="shape-options" role="group" aria-label="기본 체형">{(['slim','regular','broad'] as const).map(s=><button className={shape===s?'active':''} key={s} onClick={()=>{setShape(s);setDraft(makePreset(Number.isFinite(draft.measurements.height)?draft.measurements.height:175,s));}}><span>{s==='slim'?'슬림':s==='regular'?'보통':'넓은 체형'}</span><small>{s==='slim'?'가벼운 실루엣':s==='regular'?'기본 비율': '여유 있는 비율'}</small></button>)}</div><p className="editor-helper">기본 체형은 출발점이에요. 아래에서 내 치수로 조절해 주세요.</p>{fields(true)}</TabsContent>
 <TabsContent value="manual"><p className="editor-helper">줄자로 잰 치수를 입력해 주세요. cm 단위이며, 직접 입력한 값은 사진 추정으로 덮어쓰지 않아요.</p>{fields(false)}</TabsContent>
 <TabsContent value="photo"><div className="photo-intro"><Camera size={21}/><div><h3>정면과 측면, 두 장이면 시작.</h3><p>입력한 키와 사진 윤곽으로 초기 체형을 제안해요.</p></div></div><ul className="photo-guidance"><li>한 사람의 머리부터 발까지, 주위에 여백을 남겨 주세요.</li><li>몸의 윤곽이 드러나는 옷을 입고 팔을 몸에서 조금 떼어 주세요.</li><li>같은 자세로 정면 한 장, 옆으로 90도 돌려 한 장 촬영해 주세요.</li><li>사진은 이 기기 안에서만 분석하며 원본을 저장하지 않아요.</li></ul>
 <div className="photo-height"><label htmlFor="photo-height">맨발로 잰 키</label><div className="number-with-unit"><Input id="photo-height" type="number" min="140" max="210" value={Number.isFinite(draft.measurements.height)?draft.measurements.height:''} disabled={busy} onChange={e=>{change('height',e.target.value===''?NaN:Number(e.target.value));setResult(false);}}/>cm</div></div>
 <div className="photo-upload-grid">{(['front','side'] as const).map(kind=><div className="photo-upload" key={kind}><label><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{fileChange(kind,e.target.files?.[0]);e.target.value='';}}/>{photos[kind]?<img src={photos[kind]!.url} alt={kind==='front'?'선택한 정면사진':'선택한 측면사진'}/>:<><ImagePlus size={25}/><span>{kind==='front'?'정면사진':'측면사진'}</span><small>사진 선택</small></>}</label>{photos[kind]&&<><span className="photo-label">{kind==='front'?'정면':'측면'}</span><button disabled={busy} aria-label={`${kind==='front'?'정면':'측면'}사진 제거`} onClick={()=>{URL.revokeObjectURL(photos[kind]!.url);setPhotos(p=>{const n={...p};delete n[kind];return n;});setResult(false);}}><X size={15}/></button></>}</div>)}</div>
 <button className="analyze-button" disabled={busy||!photos.front||!photos.side||!Number.isFinite(draft.measurements.height)||draft.measurements.height<140||draft.measurements.height>210} onClick={analyze}>{busy?<><LoaderCircle size={17} className="spin"/>분석 중…</>:<><Camera size={17}/>{result?'다시 추정하기':'사진으로 체형 추정'}</>}</button>
 {busy&&<p className="editor-helper" role="status">{progress}</p>}{error&&<p className="form-error" role="alert">{error}</p>}
 {result&&<div className="photo-result"><div className="result-title"><Check size={17}/> 체형을 제안했어요. 치수를 확인해 주세요.</div>{preserved.length>0&&<p className="editor-helper">직접 입력한 {preserved.join('·')} 값은 유지했어요.</p>}<p className="editor-helper">촬영 자세와 옷의 두께에 따라 오차가 생길 수 있어요. 머리둘레는 직접 입력해 주세요.</p>{fields(false)}<label className="review-check"><Checkbox checked={reviewed} onCheckedChange={v=>setReviewed(v===true)}/><span>추정 결과를 확인하고 필요한 치수를 수정했어요.</span></label></div>}
 </TabsContent></div></Tabs>
 <div className="editor-footer">{result&&!reviewed&&tab!=='photo'&&<p className="editor-helper">사진 추정 탭에서 결과 확인에 체크한 뒤 저장해 주세요.</p>}{!valid&&<p className="form-error" role="alert">각 치수의 범위를 확인해 주세요. 허리 높이는 키의 72% 미만이어야 해요.</p>}<button className="primary-button" disabled={!canSave} onClick={()=>onSave(draft)}>내 체형 적용하고 저장</button><p className="privacy-note"><LockKeyhole size={12}/> 치수만 이 브라우저에 저장됩니다.</p><button className="text-button" onClick={onDelete} disabled={busy}><Trash2 size={13}/> 저장한 체형 삭제</button></div></SheetContent></Sheet>;
}
