'use client';

import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Eye,EyeOff,ImagePlus,PackagePlus,Pencil,Plus,Trash2,Upload,X} from 'lucide-react';
import SellerHeader from '@/components/seller-header';
import {parseOptionalNumberInput} from '@/lib/ads/client-utils';
import {SELLER_CATEGORIES,SELLER_CATEGORY_LABELS,SELLER_MEASUREMENT_FIELDS,SELLER_MEASUREMENT_KEYS,SELLER_PRODUCTS_STORAGE_KEY,emptySellerSize,normalizeSellerProductPublication,parseStoredSellerProducts,productReadiness,publishSellerProduct,sellerProductSchema,unpublishSellerProduct,upsertSellerProduct,type SellerCategory,type SellerMeasurementKey,type SellerProduct,type SellerSize} from '@/lib/seller/products';

type SizeForm={label:string}&Record<SellerMeasurementKey,string>;
type ProductForm={storeName:string;name:string;category:SellerCategory;color:string;features:string;material:string;price:string;stock:string;purchaseUrl:string;sizes:SizeForm[]};
const emptySizeForm=(label=''):SizeForm=>({label,length:'',chestFlat:'',shoulder:'',sleeve:'',waistFlat:'',hipsFlat:'',thighFlat:'',rise:'',headCirc:''});
const INITIAL_FORM:ProductForm={storeName:'오후옷장',name:'',category:'top',color:'',features:'',material:'',price:'',stock:'',purchaseUrl:'',sizes:[emptySizeForm('M')]};

function optionalDecimal(value:string){const clean=value.trim();if(!clean)return null;if(!/^\d+(?:\.\d{1,2})?$/.test(clean))return Number.NaN;return Number(clean);}
function toSizeForm(size:SellerSize):SizeForm{return {label:size.label,...Object.fromEntries(SELLER_MEASUREMENT_KEYS.map(key=>[key,size[key]===null?'':String(size[key])]))} as SizeForm;}

export default function SellerProducts(){
 const [products,setProducts]=useState<SellerProduct[]>([]),[form,setForm]=useState<ProductForm>(INITIAL_FORM),[editingId,setEditingId]=useState<string|null>(null);
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[imageUrl,setImageUrl]=useState<string|null>(null);const objectUrl=useRef<string|null>(null);
 useEffect(()=>{try{setProducts(parseStoredSellerProducts(localStorage.getItem(SELLER_PRODUCTS_STORAGE_KEY)));}catch{}},[]);
 useEffect(()=>()=>{if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);},[]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),2600);return()=>clearTimeout(timer);},[notice]);
 const fields=SELLER_MEASUREMENT_FIELDS[form.category];
 function setField<K extends keyof Omit<ProductForm,'sizes'>>(key:K,value:ProductForm[K]){setForm(previous=>({...previous,[key]:value}));}
 function setSize(index:number,key:keyof SizeForm,value:string){setForm(previous=>({...previous,sizes:previous.sizes.map((size,row)=>row===index?{...size,[key]:value}:size)}));}
 function chooseImage(file?:File){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)){setError('PNG, JPG, WEBP 이미지만 선택할 수 있어요.');return;}if(file.size>8*1024*1024){setError('이미지는 8MB 이하로 선택해 주세요.');return;}if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);objectUrl.current=URL.createObjectURL(file);setImageUrl(objectUrl.current);setError('');}
 function persist(next:SellerProduct[]){setProducts(next);try{localStorage.setItem(SELLER_PRODUCTS_STORAGE_KEY,JSON.stringify(next));return true;}catch{return false;}}
 function resetForm(){setForm({...INITIAL_FORM,sizes:[emptySizeForm('M')]});setEditingId(null);setError('');if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);objectUrl.current=null;setImageUrl(null);}
 function saveProduct(){
  if(!form.storeName.trim()||!form.name.trim()||!form.color.trim()){setError('상점명, 상품명, 색상을 모두 입력해 주세요.');return;}
  const features=form.features.split(/[,/\n]+/).map(value=>value.trim()).filter(Boolean);if(features.length<1||features.length>5){setError('핵심 특징을 1개 이상 5개 이하로 입력해 주세요.');return;}
  const price=parseOptionalNumberInput(form.price),stock=parseOptionalNumberInput(form.stock);if(Number.isNaN(price)){setError('판매가는 원 단위 숫자로 입력해 주세요.');return;}if(Number.isNaN(stock)){setError('재고는 숫자로 입력해 주세요.');return;}
  const purchaseUrl=form.purchaseUrl.trim();if(purchaseUrl&&!/^https?:\/\/[^\s]+$/i.test(purchaseUrl)){setError('구매 링크는 http:// 또는 https://로 시작하는 주소를 입력해 주세요.');return;}
  const sizes:SellerSize[]=[];
  for(const row of form.sizes){
   const hasMeasurement=SELLER_MEASUREMENT_KEYS.some(key=>row[key].trim());if(!row.label.trim()&&!hasMeasurement)continue;if(!row.label.trim()){setError('실측값을 입력한 행에는 사이즈 이름이 필요해요.');return;}
   const size=emptySellerSize(row.label.trim());
   for(const key of SELLER_MEASUREMENT_KEYS){const value=optionalDecimal(row[key]);if(Number.isNaN(value)){setError(`${row.label} 사이즈의 실측은 cm 숫자로 입력해 주세요.`);return;}size[key]=value;}
   sizes.push(size);
  }
  if(new Set(sizes.map(size=>size.label)).size!==sizes.length){setError('같은 사이즈 이름을 두 번 사용할 수 없어요.');return;}
  const existing=products.find(product=>product.id===editingId),now=new Date().toISOString();
  const candidate={version:1 as const,id:existing?.id??crypto.randomUUID(),storeName:form.storeName.trim(),name:form.name.trim(),category:form.category,color:form.color.trim(),features,material:form.material.trim()||null,priceKrw:price,stock,purchaseUrl:purchaseUrl||null,sizes,createdAt:existing?.createdAt??now,updatedAt:now,status:existing?.status??'draft' as const,publishedAt:existing?.publishedAt??null};
  const parsed=sellerProductSchema.safeParse(candidate);if(!parsed.success){setError('입력 내용을 다시 확인해 주세요.');return;}
  const normalized=normalizeSellerProductPublication(parsed.data),wasUnpublished=existing?.status==='published'&&normalized.status==='draft';
  const saved=persist(upsertSellerProduct(products,normalized));setNotice(saved?(wasUnpublished?'필수 정보가 빠져 게시를 내리고 수정 내용을 저장했어요.':existing?'상품 정보를 수정했어요.':'상품 초안을 저장했어요.'):'브라우저에 저장하지 못했어요.');resetForm();
 }
 function editProduct(product:SellerProduct){setForm({storeName:product.storeName,name:product.name,category:product.category,color:product.color,features:product.features.join(', '),material:product.material??'',price:product.priceKrw===null?'':String(product.priceKrw),stock:product.stock===null?'':String(product.stock),purchaseUrl:product.purchaseUrl??'',sizes:product.sizes.length?product.sizes.map(toSizeForm):[emptySizeForm()]});setEditingId(product.id);setError('');if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);objectUrl.current=null;setImageUrl(null);window.scrollTo({top:0,behavior:'smooth'});}
 function deleteProduct(product:SellerProduct){if(!window.confirm(`‘${product.name}’ 상품을 삭제할까요?`))return;persist(products.filter(item=>item.id!==product.id));if(editingId===product.id)resetForm();setNotice('상품을 삭제했어요.');}
 function togglePublication(product:SellerProduct){
  if(product.status==='published'){
   const next=unpublishSellerProduct(product);const saved=persist(upsertSellerProduct(products,next));setNotice(saved?'이용자 옷장에서 상품을 내렸어요.':'게시 상태를 저장하지 못했어요.');return;
  }
  const next=publishSellerProduct(product);if(!next){setNotice(`게시하려면 ${productReadiness(product).missing.join(', ')} 정보를 채워 주세요.`);return;}
  const saved=persist(upsertSellerProduct(products,next));setNotice(saved?'상품을 게시했어요. 이용자 옷장에서 바로 입어볼 수 있어요.':'게시 상태를 저장하지 못했어요.');
 }
 return <main className="seller-app"><SellerHeader active="products"/><section className="seller-page-heading"><div><span className="eyebrow">PRODUCT MANAGEMENT</span><h1>상품 등록과 관리</h1><p>광고 제작과 이용자 옷장에 사용할 상품 정보를 정리합니다.</p></div><span className="seller-local-badge">같은 브라우저에 게시</span></section>
  <section className="seller-products-layout"><article className="seller-panel seller-registration"><div className="seller-panel-heading"><div><span className="eyebrow">{editingId?'EDIT PRODUCT':'NEW PRODUCT'}</span><h2>{editingId?'상품 정보 수정':'새 상품 등록'}</h2></div>{editingId&&<button type="button" onClick={resetForm}><X/>수정 취소</button>}</div>
   <div className="seller-product-form"><section><h3>상품 이미지</h3><div className="seller-image-field">{imageUrl?<img src={imageUrl} alt="등록 상품 미리보기"/>:<div><ImagePlus/><span>상품 이미지 미리보기</span></div>}<label><Upload/>이미지 선택<input type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>chooseImage(event.target.files?.[0])}/></label></div><p>이미지는 현재 미리보기에만 사용하며 저장하지 않습니다.</p></section>
    <section><h3>기본 정보</h3><div className="seller-form-grid"><label><span>상점명 *</span><input value={form.storeName} maxLength={40} onChange={event=>setField('storeName',event.target.value)}/></label><label><span>상품명 *</span><input value={form.name} maxLength={80} placeholder="예: 스트라이프 반팔 티셔츠" onChange={event=>setField('name',event.target.value)}/></label><label><span>카테고리 *</span><select value={form.category} onChange={event=>setField('category',event.target.value as SellerCategory)}>{SELLER_CATEGORIES.map(category=><option value={category} key={category}>{SELLER_CATEGORY_LABELS[category]}</option>)}</select></label><label><span>색상 *</span><input value={form.color} maxLength={40} placeholder="예: 네이비" onChange={event=>setField('color',event.target.value)}/></label><label className="seller-wide-field"><span>핵심 특징 * <small>쉼표로 구분 · 최대 5개</small></span><textarea value={form.features} maxLength={504} placeholder="예: 가로 스트라이프, 라운드넥, 여유 있는 실루엣" onChange={event=>setField('features',event.target.value)}/></label><label className="seller-wide-field"><span>소재</span><input value={form.material} maxLength={100} placeholder="확인한 경우에만 입력" onChange={event=>setField('material',event.target.value)}/></label><label><span>판매가</span><input inputMode="numeric" value={form.price} placeholder="29000" onChange={event=>setField('price',event.target.value)}/><small>원 단위</small></label><label><span>재고</span><input inputMode="numeric" value={form.stock} placeholder="10" onChange={event=>setField('stock',event.target.value)}/><small>현재 판매 가능 수량</small></label><label className="seller-wide-field"><span>상점 구매 링크 <small>선택</small></span><input inputMode="url" value={form.purchaseUrl} maxLength={500} placeholder="예: https://smartstore.naver.com/myshop/products/123" onChange={event=>setField('purchaseUrl',event.target.value)}/><small>스마트스토어·자사몰 등 실제 상품 페이지를 연결할 수 있어요.</small></label></div></section>
    <section><div className="seller-size-heading"><div><h3>사이즈별 실측</h3><p>단위 cm · 상의/하의의 너비 항목은 단면 기준</p></div><button type="button" disabled={form.sizes.length>=6} onClick={()=>setForm(previous=>({...previous,sizes:[...previous.sizes,emptySizeForm()]}))}><Plus/>행 추가</button></div><div className="seller-size-scroll"><table><thead><tr><th>사이즈</th>{fields.map(field=><th key={field.key}>{field.label}</th>)}<th><span className="sr-only">행 삭제</span></th></tr></thead><tbody>{form.sizes.map((size,index)=><tr key={index}><td><input aria-label={`${index+1}번째 사이즈 이름`} value={size.label} placeholder="M" maxLength={20} onChange={event=>setSize(index,'label',event.target.value)}/></td>{fields.map(field=><td key={field.key}><input aria-label={`${size.label||index+1} ${field.label}`} inputMode="decimal" value={size[field.key]} placeholder="-" onChange={event=>setSize(index,field.key,event.target.value)}/></td>)}<td><button type="button" aria-label={`${size.label||index+1} 사이즈 행 삭제`} disabled={form.sizes.length===1} onClick={()=>setForm(previous=>({...previous,sizes:previous.sizes.filter((_,row)=>row!==index)}))}><Trash2/></button></td></tr>)}</tbody></table></div><p className="seller-size-note">게시 준비 판정에는 {form.category==='hat'?'머리둘레':form.category==='top'?'총장과 가슴단면':'총장과 허리단면'}이 필요합니다. 초안은 실측 없이도 저장할 수 있어요.</p></section>
   </div>{error&&<div className="seller-form-error" role="alert">{error}</div>}<div className="seller-form-actions"><button type="button" className="seller-save-button" onClick={saveProduct}><PackagePlus/>{editingId?'수정 내용 저장':'상품 초안 저장'}</button><span>저장 후 오른쪽 상품 목록에서 게시할 수 있습니다.</span></div>
  </article>
  <aside className="seller-panel seller-catalog"><div className="seller-panel-heading"><div><span className="eyebrow">MY PRODUCTS</span><h2>등록 상품 <b>{products.length}</b></h2></div><a href="/wardrobe">이용자 옷장 보기 <ArrowRight/></a></div>{products.length===0?<div className="seller-empty compact"><PackagePlus/><h3>상품 목록이 비어 있어요</h3><p>왼쪽에서 첫 상품 초안을 저장해 보세요.</p></div>:<div className="seller-catalog-list">{products.map(product=>{const state=productReadiness(product),published=product.status==='published';return <article key={product.id}><div className="seller-catalog-title"><span>{SELLER_CATEGORY_LABELS[product.category].slice(0,1)}</span><div><small>{product.storeName}</small><strong>{product.name}</strong><p>{SELLER_CATEGORY_LABELS[product.category]} · {product.color}</p></div><em className={published?'published':state.ready?'ready':'draft'}>{published?'게시 중':state.ready?'게시 준비':'작성 중'}</em></div><div className="seller-progress"><span style={{width:`${state.percent}%`}}/></div><div className="seller-catalog-meta"><span>{product.priceKrw===null?'가격 미입력':`${product.priceKrw.toLocaleString('ko-KR')}원`}</span><span>{product.stock===null?'재고 미입력':product.stock===0?'품절':`재고 ${product.stock}`}</span><span>사이즈 {product.sizes.length}</span></div>{!state.ready&&<p className="seller-missing">남은 정보: {state.missing.join(', ')}</p>}<div className="seller-catalog-actions"><button type="button" className={published?'unpublish':'publish'} onClick={()=>togglePublication(product)}>{published?<><EyeOff/>게시 내리기</>:<><Eye/>옷장에 게시</>}</button><button type="button" onClick={()=>editProduct(product)}><Pencil/>수정</button><button type="button" onClick={()=>deleteProduct(product)}><Trash2/>삭제</button><a href={`/seller/ads?product=${encodeURIComponent(product.id)}`}>광고 만들기 <ArrowRight/></a></div></article>;})}</div>}</aside>
  </section><footer className="seller-footer"><span>FITROOM SELLER · 상품 등록 프로토타입</span><span>게시 상품은 같은 브라우저의 이용자 옷장에 표시됩니다. 다른 기기와는 아직 공유되지 않습니다.</span></footer>{notice&&<div className="toast" role="status">{notice}</div>}
 </main>;
}
