'use client';

import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,BookmarkPlus,Box,CheckCircle2,Clock,Eye,Heart,PackagePlus,Shirt,Sparkles,Store,TrendingUp} from 'lucide-react';
import SellerHeader from '@/components/seller-header';
import {SELLER_CATEGORY_LABELS,SELLER_PRODUCTS_STORAGE_KEY,parseStoredSellerProducts,productReadiness,type SellerProduct} from '@/lib/seller/products';
import {createWardrobeCollection,parseStoredWardrobeCollection,WARDROBE_COLLECTION_STORAGE_KEY,type WardrobeCollection} from '@/lib/wardrobe/collection';
import {createInterestLog,parseStoredInterestLog,summarizeProductInterest,WARDROBE_INTEREST_STORAGE_KEY,type InterestLog,type InterestSignalType} from '@/lib/wardrobe/interest';

const SIGNAL_LABELS:Record<InterestSignalType,string>={favorite_add:'상품을 찜했어요',try_on:'아바타에게 입혀봤어요',recommendation_open:'추천에서 상품을 열었어요',look_save:'코디에 저장했어요'};

function signalTime(value:string){return new Intl.DateTimeFormat('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value));}

export default function SellerDashboard(){
 const [products,setProducts]=useState<SellerProduct[]>([]);
 const [collection,setCollection]=useState<WardrobeCollection>(()=>createWardrobeCollection());
 const [interestLog,setInterestLog]=useState<InterestLog>(()=>createInterestLog());

 useEffect(()=>{
  const sync=()=>{try{setProducts(parseStoredSellerProducts(localStorage.getItem(SELLER_PRODUCTS_STORAGE_KEY)));setCollection(parseStoredWardrobeCollection(localStorage.getItem(WARDROBE_COLLECTION_STORAGE_KEY)));setInterestLog(parseStoredInterestLog(localStorage.getItem(WARDROBE_INTEREST_STORAGE_KEY)));}catch{}};
  sync();const handleStorage=()=>sync();window.addEventListener('storage',handleStorage);return()=>window.removeEventListener('storage',handleStorage);
 },[]);

 const ready=products.filter(product=>productReadiness(product).ready).length;
 const published=products.filter(product=>product.status==='published').length;
 const wardrobeIds=useMemo(()=>products.map(product=>`seller:${product.id}`),[products]);
 const interestRows=useMemo(()=>summarizeProductInterest(wardrobeIds,collection,interestLog),[wardrobeIds,collection,interestLog]);
 const productByWardrobeId=useMemo(()=>new Map<string,SellerProduct>(products.map(product=>[`seller:${product.id}`,product])),[products]);
 const relevantEvents=useMemo(()=>interestLog.events.flatMap(event=>{const ids=event.productIds.filter(id=>productByWardrobeId.has(id));return ids.length?[{...event,productIds:ids}]:[];}),[interestLog,productByWardrobeId]);
 const signals={favorites:interestRows.reduce((sum,row)=>sum+row.favorite,0),savedLooks:interestRows.reduce((sum,row)=>sum+row.savedLooks,0),tryOns:interestRows.reduce((sum,row)=>sum+row.tryOns,0),recommendationOpens:interestRows.reduce((sum,row)=>sum+row.recommendationOpens,0)};
 const signalTotal=signals.favorites+signals.savedLooks+signals.tryOns+signals.recommendationOpens;
 const maxScore=Math.max(1,...interestRows.map(row=>row.score));

 return <main className="seller-app"><SellerHeader active="overview"/><section className="seller-page-heading"><div><span className="eyebrow">SMALL BUSINESS WORKSPACE</span><h1>소상공인 판매자 센터</h1><p>상품을 등록해 3D 옷장에 게시하고, 내 상점으로 고객을 연결하세요.</p></div><a className="seller-primary-link" href="/seller/products"><PackagePlus/>상품 등록하기</a></section>
  <section className="seller-stats" aria-label="판매자 현황"><article><span><Box/></span><div><small>등록 상품</small><strong>{products.length}</strong><p>이 브라우저에 저장된 상품</p></div></article><article><span><CheckCircle2/></span><div><small>게시 준비</small><strong>{ready}</strong><p>가격·재고·필수 실측 완료</p></div></article><article><span><Eye/></span><div><small>게시 중</small><strong>{published}</strong><p>이용자 옷장에 공개된 상품</p></div></article><article><span><TrendingUp/></span><div><small>관심 신호</small><strong>{signalTotal}</strong><p>이 기기의 찜·코디·체험 반응</p></div></article></section>
  <section className="seller-interest-panel" aria-labelledby="seller-interest-title"><header><div><span className="eyebrow">LOCAL SHOPPER SIGNALS</span><h2 id="seller-interest-title">이용자가 반응한 상품</h2><p>내 상품이 찜·저장 코디·입어보기·추천 클릭에 얼마나 연결됐는지 확인하세요.</p></div><span><Sparkles/>이 브라우저의 시연 데이터</span></header><div className="interest-metrics"><article><Heart/><span><small>현재 찜</small><strong>{signals.favorites}</strong></span></article><article><BookmarkPlus/><span><small>저장 코디 포함</small><strong>{signals.savedLooks}</strong></span></article><article><Shirt/><span><small>입어보기</small><strong>{signals.tryOns}</strong></span></article><article><Sparkles/><span><small>추천 클릭</small><strong>{signals.recommendationOpens}</strong></span></article></div><div className="interest-content"><section className="interest-ranking" aria-label="상품별 관심도"><div className="interest-subheading"><strong>상품별 관심도</strong><span>찜 4 · 코디 3 · 추천 2 · 입어보기 1점</span></div>{products.length===0?<div className="interest-empty"><PackagePlus/><strong>먼저 상품을 등록해 주세요</strong><p>게시한 판매자 상품에 발생한 반응이 이곳에 모입니다.</p></div>:<div className="interest-product-list">{interestRows.map(row=>{const item=productByWardrobeId.get(row.productId)!;return <article key={row.productId}><span className="interest-product-symbol">{SELLER_CATEGORY_LABELS[item.category].slice(0,1)}</span><div className="interest-product-main"><span><strong>{item.name}</strong><small>{SELLER_CATEGORY_LABELS[item.category]} · {item.status==='published'?'게시 중':'게시 전'}</small></span><div className="interest-score-track" aria-label={`${item.name} 관심 점수 ${row.score}점`}><i style={{width:`${row.score/maxScore*100}%`}}/></div><span className="interest-chips"><b><Heart/> {row.favorite}</b><b><BookmarkPlus/> {row.savedLooks}</b><b><Shirt/> {row.tryOns}</b><b><Sparkles/> {row.recommendationOpens}</b></span></div><span className="interest-score">{row.score}<small>점</small></span></article>;})}</div>}</section><aside className="interest-activity"><div className="interest-subheading"><strong>최근 활동</strong><span><Clock/>최신순</span></div>{relevantEvents.length===0?<div className="interest-empty compact"><TrendingUp/><strong>아직 동작 기록이 없어요</strong><p>이용자 화면에서 상품을 입어보거나 추천을 열면 기록됩니다.</p></div>:<ol>{relevantEvents.slice(0,5).map(event=><li key={event.id}><span className={`signal-icon signal-${event.type}`}>{event.type==='try_on'?<Shirt/>:event.type==='recommendation_open'?<Sparkles/>:event.type==='look_save'?<BookmarkPlus/>:<Heart/>}</span><div><strong>{SIGNAL_LABELS[event.type]}</strong><span>{event.productIds.map(id=>productByWardrobeId.get(id)?.name).filter(Boolean).join(' · ')}</span><small>{signalTime(event.occurredAt)}</small></div></li>)}</ol>}</aside></div><footer><span>이 수치는 실제 방문자 수나 판매량이 아니며, 현재 기기에서 기능을 시험한 반응만 보여줍니다.</span><a href="/wardrobe">이용자 화면에서 체험하기 <ArrowRight/></a></footer></section>
  <section className="seller-dashboard-grid"><article className="seller-panel"><div className="seller-panel-heading"><div><span className="eyebrow">PRODUCTS</span><h2>최근 상품</h2></div><a href="/seller/products">전체 관리 <ArrowRight/></a></div>{products.length===0?<div className="seller-empty"><PackagePlus/><h3>아직 등록한 상품이 없어요</h3><p>첫 상품의 기본 정보와 사이즈 실측을 입력해 보세요.</p><a href="/seller/products">첫 상품 등록하기</a></div>:<div className="seller-product-list">{products.slice(0,4).map(product=>{const state=productReadiness(product),published=product.status==='published';return <article key={product.id}><span className="seller-product-symbol">{SELLER_CATEGORY_LABELS[product.category].slice(0,1)}</span><div><strong>{product.name}</strong><small>{product.storeName} · {SELLER_CATEGORY_LABELS[product.category]} · {product.color}</small></div><span className={published?'published':state.ready?'ready':'draft'}>{published?'게시 중':state.ready?'게시 준비':'작성 중'}</span><a href={`/seller/ads?product=${encodeURIComponent(product.id)}`} aria-label={`${product.name} 광고 만들기`}>광고 만들기</a></article>;})}</div>}</article>
   <aside className="seller-panel seller-next"><span className="eyebrow">WORKFLOW</span><h2>판매자 작업 순서</h2><ol><li><b>01</b><div><strong>상품 정보 등록</strong><span>가격·재고·색상·특징 입력</span></div></li><li><b>02</b><div><strong>사이즈 실측 입력</strong><span>카테고리별 필수 치수 확인</span></div></li><li><b>03</b><div><strong>이용자 옷장에 게시</strong><span>3D 참고 실루엣과 핏 비교 확인</span></div></li><li><b>04</b><div><strong>가상 매장 꾸미기</strong><span>테마 선택과 상품 진열 위치 배치</span></div></li><li><b>05</b><div><strong>AI 광고 초안 제작</strong><span>선택 상품을 자동으로 불러오기</span></div></li></ol><a className="seller-store-cta" href="/seller/store"><Store/>가상 매장 꾸미기 <ArrowRight/></a><p>계정 동기화에서 상품과 매장 설정을 서버에 저장하면 다른 기기에서도 이어서 작업할 수 있습니다.</p></aside>
  </section><footer className="seller-footer"><span>FITROOM SELLER · 의류 소상공인을 위한 작업공간</span><span>상품 텍스트와 매장 설정은 계정별 서버 동기화를 지원합니다.</span></footer>
 </main>;
}
