'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Check,ChevronLeft,ChevronRight,SlidersHorizontal,Shirt,X,Info,Plus,ScanLine,Sparkles} from 'lucide-react';
import {useWardrobeTools} from '@/lib/wardrobe/webmcp';
import AvatarView from '@/components/avatar-view';
import BodyEditor from '@/components/body-editor';
import {PRODUCTS,SLOT_LABELS,getProduct} from '@/lib/wardrobe/catalog';
import {DEFAULT_BODY,parseStoredBody,STORAGE_KEY,sourceLabel} from '@/lib/wardrobe/body';
import {estimateFit,wear,remove} from '@/lib/wardrobe/fit';
import type {BodyProfile,Outfit,Product,Slot} from '@/lib/wardrobe/types';
export default function Wardrobe(){
 const [body,setBody]=useState(DEFAULT_BODY),[saved,setSaved]=useState(false),[editor,setEditor]=useState(false);
 const [outfit,setOutfit]=useState<Outfit>({top:{productId:'6170660',size:'화이트M'},bottom:{productId:'3504218',size:'30'}});
 const [selected,setSelected]=useState('6170660'),[sizes,setSizes]=useState<Record<string,string>>({}),[notice,setNotice]=useState('');
 const product=getProduct(selected)??PRODUCTS[0];const selectedSize=sizes[product.id]??(outfit[product.slot]?.productId===product.id?outfit[product.slot]?.size:product.defaultSize);
 const size=product.sizes.find(s=>s.label===selectedSize)??product.sizes.find(s=>s.label===product.defaultSize)!;
 const fit=estimateFit(body,product,size),rowRefs=useRef<Partial<Record<Slot,HTMLDivElement|null>>>({});
 useEffect(()=>{try{const b=parseStoredBody(localStorage.getItem(STORAGE_KEY));if(b){setBody(b);setSaved(true);}}catch{}},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3200);return()=>clearTimeout(t);},[notice]);
 function equip(p:Product,label?:string){const s=label??sizes[p.id]??p.defaultSize;setOutfit(o=>wear(o,p,s));setSelected(p.id);setSizes(v=>({...v,[p.id]:s}));setNotice(`${SLOT_LABELS[p.slot]}를 입었어요.`);}
 function chooseSize(label:string){setSizes(v=>({...v,[product.id]:label}));if(outfit[product.slot]?.productId===product.id)setOutfit(o=>wear(o,product,label));}
 function saveBody(b:BodyProfile){setBody(b);try{localStorage.setItem(STORAGE_KEY,JSON.stringify(b));setSaved(true);setNotice('이 브라우저에 내 체형을 저장했어요.');}catch{setSaved(false);setNotice('기기에 저장하지 못했어요. 이번 사용 중에는 적용됩니다.');}setEditor(false);}
 function deleteBody(){try{localStorage.removeItem(STORAGE_KEY);}catch{setNotice('저장된 체형을 삭제하지 못했어요. 브라우저 설정을 확인해 주세요.');return;}setBody(DEFAULT_BODY);setSaved(false);setNotice('저장한 체형을 삭제했어요. 기본 체형으로 돌아갑니다.');setEditor(false);}
 useWardrobeTools({body,outfit},items=>{setOutfit(previous=>items.reduce((o,item)=>wear(o,getProduct(item.productId)!,item.size),previous));setSizes(previous=>({...previous,...Object.fromEntries(items.map(i=>[i.productId,i.size]))}));setSelected(items[items.length-1].productId);setNotice('선택한 옷을 입었어요.');});
 return <main className="fitroom-app">
  <header className="app-header"><a className="brand" href="/" aria-label="FITROOM 역할 선택으로 이동"><span className="brand-mark"><ScanLine size={23}/></span>fitroom<span className="brand-period">.</span></a><div className="header-center"><span className="nav-active">이용자 3D 옷장</span><span className="header-divider"/>나의 체형, 나의 스타일</div><a className="body-button" href="/seller"><Sparkles size={16}/> 판매자 광고 만들기</a></header>
  <div className="page-heading"><div><span className="eyebrow">YOUR PERSONAL WARDROBE</span><h1>오늘은, 어떻게 입을까요?</h1></div><span className="collection-count">CASUAL COLLECTION <b>08</b></span></div>
  <section className="workspace"><div className="fitting-panel"><AvatarView body={body} outfit={outfit} onDrop={id=>{const p=getProduct(id);if(p)equip(p);}}/><div className="body-strip"><div className="body-strip-title"><span className="body-dot"/><span>{saved?'저장된 내 체형':'기본 체형'}</span><span className="body-mini">{saved?'이 브라우저에 저장됨':'내 치수로 바꿔보세요'}</span></div><div className="body-numbers"><span>키 <b>{body.measurements.height}</b><small>cm</small></span><span>가슴 <b>{body.measurements.chest}</b></span><span>허리 <b>{body.measurements.waist}</b></span><button onClick={()=>setEditor(true)} aria-label="체형 수정"><SlidersHorizontal size={15}/></button></div></div></div>
  <aside className="wardrobe-panel" aria-label="부위별 옷장"><div className="wardrobe-heading"><div><Shirt size={18}/><h2>나의 옷장</h2></div><span>끌어서 입어보기</span></div>
  {(['hat','top','bottom'] as Slot[]).map((slot,index)=><section className="closet-section" key={slot}><div className="section-heading"><h3><span>0{index+1}</span>{SLOT_LABELS[slot]}<small>{PRODUCTS.filter(p=>p.slot===slot).length}</small></h3><div className="scroll-buttons"><button aria-label={`${SLOT_LABELS[slot]} 이전 상품`} onClick={()=>rowRefs.current[slot]?.scrollBy({left:-220,behavior:'smooth'})}><ChevronLeft size={15}/></button><button aria-label={`${SLOT_LABELS[slot]} 다음 상품`} onClick={()=>rowRefs.current[slot]?.scrollBy({left:220,behavior:'smooth'})}><ChevronRight size={15}/></button></div></div><div className="product-row" ref={el=>{rowRefs.current[slot]=el;}}>{PRODUCTS.filter(p=>p.slot===slot).map(p=>{const worn=outfit[slot]?.productId===p.id;return <article key={p.id} className={`product-card ${selected===p.id?'selected':''} ${worn?'worn':''}`} draggable onDragStart={e=>{e.dataTransfer.setData('text/plain',p.id);e.dataTransfer.effectAllowed='copy';}}><button className="product-photo" aria-label={`${p.brand} ${p.name} 상세 보기`} onClick={()=>setSelected(p.id)}><img src={p.image} alt={`${p.name} ${p.colorName}의 참고용 3D 의상`} draggable={false}/>{worn&&<span className="wearing-badge"><Check size={11}/>착용 중</span>}<span className="swatch" style={{background:p.color}}/></button><button className="product-description" onClick={()=>setSelected(p.id)}><span>{p.brand}</span><strong>{p.name}</strong></button><button className={`wear-button ${worn?'is-worn':''}`} onClick={()=>worn?(setOutfit(o=>remove(o,slot)),setNotice(`${SLOT_LABELS[slot]}를 벗었어요.`)):equip(p)} aria-label={`${p.name} ${worn?'벗기':'입어보기'}`}>{worn?<><X size={12}/>벗기</>:<><Plus size={12}/>입어보기</>}</button></article>;})}</div></section>)}
  <p className="catalog-note"><Info size={13}/> 상품의 색상·실루엣을 단순화한 3D 이미지예요.</p></aside></section>
  <section className="selection-panel" aria-label="선택한 상품과 실측 비교"><div className="selected-product"><img src={product.image} alt=""/><div><span className="eyebrow">SELECTED ITEM</span><p className="selected-brand">{product.brand}</p><h2>{product.name}</h2><span className="color-label"><i style={{background:product.color}}/>{product.colorName}</span></div></div><div className="size-section"><div className="label-row"><h3>사이즈 선택</h3><span>상품 실측 기준</span></div><div className="size-options" role="group" aria-label="상품 사이즈">{product.sizes.map(s=><button key={s.label} className={size.label===s.label?'active':''} aria-pressed={size.label===s.label} onClick={()=>chooseSize(s.label)}>{s.label}</button>)}</div><button className="text-button" onClick={()=>equip(product,size.label)}><Plus size={13}/> 이 사이즈 입어보기</button></div><div className="fit-section"><div className="label-row"><h3>예상 핏</h3><span className="estimate-badge">검증 전 추정</span></div><div className="fit-values">{[...fit.filter(f=>f.kind==='difference'),...fit.filter(f=>f.label.endsWith('총장')),...fit.filter(f=>f.kind==='unavailable'),...fit.filter(f=>f.kind==='length'&&!f.label.endsWith('총장'))].slice(0,2).map(f=><div key={f.label}><span>{f.label}</span><strong className={f.value!==null&&f.kind==='difference'&&f.value<0?'negative':''}>{f.value===null?'판단 보류':`${f.kind==='difference'&&f.value>0?'+':''}${f.value}`}<small>{f.unit}</small></strong>{f.source&&<small>{sourceLabel[f.source]}</small>}</div>)}</div></div><a className="purchase-button" href={product.url} target="_blank" rel="noopener noreferrer">무신사에서 보기<ArrowUpRight size={19}/></a></section>
  <details className="measurement-details"><summary><Info size={14}/> 실측 정보와 판단 근거 확인<ChevronRight size={14}/></summary><div className="measurement-content"><div><h3>상품 실측 · cm</h3><div className="measurement-table">{Object.entries(size).filter(([k,v])=>k!=='label'&&v!==undefined).map(([k,v])=><div key={k}><span>{({length:'총장',chestFlat:'가슴단면',chestCirc:'가슴둘레',shoulder:'어깨너비',sleeve:'소매길이',waistFlat:'허리단면',hipsFlat:'엉덩이단면',thighFlat:'허벅지단면',rise:'밑위',hemFlat:'밑단단면',headCirc:'머리둘레'} as Record<string,string>)[k]??k}</span><b>{String(v)}</b></div>)}</div><p>{product.note}</p><a href={product.url} target="_blank" rel="noopener noreferrer">실측 출처 · 무신사 ↗</a><small>확인일 {product.checkedAt} · 현재 가격과 재고는 무신사에서 확인하세요.</small></div><div><h3>계산 방법과 한계</h3>{fit.map(f=><p key={f.label}><b>{f.label}</b> — {f.detail}</p>)}<p>3D는 참고 실루엣입니다. 원단의 늘어남·주름·착용감을 재현하지 않으며 실제 착용 결과로 검증되지 않았어요.</p></div></div></details>
  <footer className="app-footer"><span>FITROOM · 입어보고, 발견하는 나의 취향.</span><span>무신사와 독립적으로 제작된 가상 피팅 서비스</span></footer>
  <BodyEditor open={editor} onOpenChange={setEditor} body={body} onSave={saveBody} onDelete={deleteBody}/>{notice&&<div className="toast" role="status"><Check size={16}/>{notice}</div>}
 </main>;
}
