'use client';

import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowUpRight,Check,ChevronLeft,ChevronRight,DoorOpen,Info,MapPin,Plus,ScanLine,Shirt,ShoppingBag,SlidersHorizontal,Sparkles,Store,X} from 'lucide-react';
import AvatarView from '@/components/avatar-view';
import BodyEditor from '@/components/body-editor';
import {publishedSellerCatalog} from '@/lib/seller/catalog';
import {parseStoredSellerProducts,SELLER_PRODUCTS_STORAGE_KEY} from '@/lib/seller/products';
import {DEFAULT_BODY,parseStoredBody,sourceLabel,STORAGE_KEY} from '@/lib/wardrobe/body';
import {PRODUCTS,SLOT_LABELS} from '@/lib/wardrobe/catalog';
import {estimateFit,remove,wear} from '@/lib/wardrobe/fit';
import {buildVirtualStores} from '@/lib/wardrobe/stores';
import type {BodyProfile,Outfit,Product,Slot} from '@/lib/wardrobe/types';
import {useWardrobeTools} from '@/lib/wardrobe/webmcp';

const MEASUREMENT_LABELS:Record<string,string>={length:'총장',chestFlat:'가슴단면',chestCirc:'가슴둘레',shoulder:'어깨너비',sleeve:'소매길이',waistFlat:'허리단면',hipsFlat:'엉덩이단면',thighFlat:'허벅지단면',rise:'밑위',hemFlat:'밑단단면',headCirc:'머리둘레'};
const SLOT_ORDER:Slot[]=['hat','top','bottom'];

export default function Wardrobe(){
 const [body,setBody]=useState(DEFAULT_BODY),[saved,setSaved]=useState(false),[editor,setEditor]=useState(false);
 const [outfit,setOutfit]=useState<Outfit>({top:{productId:'6170660',size:'M'},bottom:{productId:'3504218',size:'30'}});
 const [selected,setSelected]=useState('6170660'),[sizes,setSizes]=useState<Record<string,string>>({}),[notice,setNotice]=useState('');
 const [sellerProducts,setSellerProducts]=useState<Product[]>([]),[activeStore,setActiveStore]=useState<string|null>(null),[enteringStore,setEnteringStore]=useState<string|null>(null);
 const catalog=useMemo(()=>[...sellerProducts,...PRODUCTS],[sellerProducts]);
 const stores=useMemo(()=>buildVirtualStores(catalog),[catalog]);
 const storeProducts=useMemo(()=>activeStore?catalog.filter(item=>item.brand===activeStore):[],[activeStore,catalog]);
 const activeVirtualStore=stores.find(store=>store.name===activeStore);
 const product=catalog.find(item=>item.id===selected)??storeProducts[0]??PRODUCTS[0];
 const selectedSize=sizes[product.id]??(outfit[product.slot]?.productId===product.id?outfit[product.slot]?.size:product.defaultSize);
 const size=product.sizes.find(item=>item.label===selectedSize)??product.sizes.find(item=>item.label===product.defaultSize)!;
 const fit=estimateFit(body,product,size),rowRefs=useRef<Partial<Record<Slot,HTMLDivElement|null>>>({}),rackRefs=useRef<Partial<Record<Slot,HTMLElement|null>>>({}),entryTimer=useRef<ReturnType<typeof setTimeout>|null>(null);

 useEffect(()=>{
  const syncSellerProducts=()=>{try{setSellerProducts(publishedSellerCatalog(parseStoredSellerProducts(localStorage.getItem(SELLER_PRODUCTS_STORAGE_KEY))));}catch{setSellerProducts([]);}};
  const hydrate=window.setTimeout(()=>{try{const stored=parseStoredBody(localStorage.getItem(STORAGE_KEY));if(stored){setBody(stored);setSaved(true);}}catch{}syncSellerProducts();},0);
  const handleStorage=(event:StorageEvent)=>{if(event.key===SELLER_PRODUCTS_STORAGE_KEY)syncSellerProducts();};
  window.addEventListener('storage',handleStorage);return()=>{window.clearTimeout(hydrate);window.removeEventListener('storage',handleStorage);};
 },[]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),3200);return()=>clearTimeout(timer);},[notice]);
 useEffect(()=>()=>{if(entryTimer.current)clearTimeout(entryTimer.current);},[]);

 function lookup(id:string){return catalog.find(item=>item.id===id);}
 function enterStore(name:string){const first=catalog.find(item=>item.brand===name);if(!first||enteringStore)return;setEnteringStore(name);entryTimer.current=setTimeout(()=>{setActiveStore(name);setSelected(first.id);setEnteringStore(null);setNotice(`${name} 가상 매장에 입장했어요.`);window.scrollTo({top:0,behavior:'smooth'});},620);}
 function leaveStore(){setActiveStore(null);setNotice('상점 거리로 나왔어요. 입어본 옷은 그대로 유지됩니다.');window.scrollTo({top:0,behavior:'smooth'});}
 function equip(item:Product,label?:string){const chosen=label??sizes[item.id]??item.defaultSize;setOutfit(current=>wear(current,item,chosen));setSelected(item.id);setSizes(current=>({...current,[item.id]:chosen}));setNotice(`${item.brand}의 ${item.name}을 입었어요.`);}
 function chooseSize(label:string){setSizes(current=>({...current,[product.id]:label}));if(outfit[product.slot]?.productId===product.id)setOutfit(current=>wear(current,product,label));}
 function saveBody(next:BodyProfile){setBody(next);try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));setSaved(true);setNotice('내 체형을 피팅 패스에 저장했어요.');}catch{setSaved(false);setNotice('기기에 저장하지 못했어요. 이번 사용 중에는 적용됩니다.');}setEditor(false);}
 function deleteBody(){try{localStorage.removeItem(STORAGE_KEY);}catch{setNotice('저장된 체형을 삭제하지 못했어요. 브라우저 설정을 확인해 주세요.');return;}setBody(DEFAULT_BODY);setSaved(false);setNotice('저장한 체형을 삭제했어요. 기본 체형으로 돌아갑니다.');setEditor(false);}

 useWardrobeTools({body,outfit},items=>{
  setOutfit(previous=>items.reduce((current,item)=>{const found=lookup(item.productId);return found?wear(current,found,item.size):current;},previous));
  setSizes(previous=>({...previous,...Object.fromEntries(items.map(item=>[item.productId,item.size]))}));
  setSelected(items[items.length-1].productId);setNotice('선택한 옷을 입었어요.');
 });

 if(!activeStore)return <main className="fitroom-app market-app">
  <header className="app-header"><Link className="brand" href="/" aria-label="FITROOM 역할 선택으로 이동"><span className="brand-mark"><ScanLine size={23}/></span>fitroom<span className="brand-period">.</span></Link><div className="header-center"><span className="nav-active">가상 상점 거리</span><span className="header-divider"/>소상공인 패션 월드</div><Link className="body-button" href="/seller"><Sparkles size={16}/> 판매자 센터</Link></header>
  <section className="market-hero"><div className="market-vista" aria-hidden="true"><span className="vista-building vista-left"><i/><i/><i/></span><span className="vista-building vista-right"><i/><i/><i/></span><span className="vista-gate">fitroom.<small>VIRTUAL FASHION STREET</small></span><span className="vista-path"/></div><div className="market-copy"><span className="eyebrow">VIRTUAL FASHION STREET</span><h1>어느 옷가게에<br/>들어가 볼까요?</h1><p>상점 문을 열고 들어가 옷걸이에서 상품을 고른 뒤,<br/>내 체형의 아바타에게 바로 입혀보세요.</p><div className="market-status"><span><MapPin/>가상 상점 {stores.length}곳</span><span><Shirt/>입어볼 옷 {catalog.length}벌</span></div></div><aside className="fit-pass"><div><span>MY FIT PASS</span><strong>{body.measurements.height}<small>cm</small></strong><p>{saved?'저장된 내 체형으로 입장합니다.':'기본 체형으로 둘러볼 수 있어요.'}</p></div><dl><div><dt>가슴</dt><dd>{body.measurements.chest}</dd></div><div><dt>허리</dt><dd>{body.measurements.waist}</dd></div><div><dt>엉덩이</dt><dd>{body.measurements.hips}</dd></div></dl><button type="button" onClick={()=>setEditor(true)}><SlidersHorizontal/>체형 설정</button></aside></section>
  <section className="store-street" aria-labelledby="store-street-title"><div className="street-heading"><div><span className="eyebrow">SHOP STREET</span><h2 id="store-street-title">오늘 문을 연 상점</h2></div><span>매장을 선택해 입장하세요</span></div><div className="storefront-grid">{stores.map((store,index)=><button type="button" className="storefront-card" key={store.name} onClick={()=>enterStore(store.name)} disabled={Boolean(enteringStore)} style={{'--store-accent':store.accent} as CSSProperties} aria-label={`${store.name} 가상 매장 입장`}><div className="storefront-top"><span>{String(index+1).padStart(2,'0')}</span>{store.hasLiveSellerItems&&<em>NEW SELLER</em>}<b>OPEN</b></div><div className="storefront-visual"><div className="storefront-sign"><strong>{store.name}</strong><small>FITROOM SELECT SHOP</small></div><div className="storefront-window">{store.products.slice(0,3).map((item,itemIndex)=><span key={item.id} style={{zIndex:3-itemIndex}}><img src={item.image} alt=""/></span>)}</div><span className="storefront-door"><DoorOpen/><small>ENTER</small></span></div><div className="storefront-info"><small>{store.slots.map(slot=>SLOT_LABELS[slot]).join(' · ')}</small><h3>{store.name}</h3><p>{store.products.length}개의 상품을 입어볼 수 있어요.</p><span className="enter-store">매장 입장 <DoorOpen/></span></div></button>)}</div></section>
  <footer className="app-footer"><span>FITROOM METAVERSE · 작은 상점의 옷을 내 체형으로.</span><span>가상 매장과 상품은 실제 판매자 게시 정보에 따라 확장됩니다.</span></footer>
  <BodyEditor open={editor} onOpenChange={setEditor} body={body} onSave={saveBody} onDelete={deleteBody}/>{enteringStore&&<div className="store-entry-transition" role="status" aria-live="polite"><div><span>ENTERING STORE</span><DoorOpen/><strong>{enteringStore}</strong><small>가상 매장으로 들어가는 중</small></div></div>}{notice&&<div className="toast" role="status"><Check size={16}/>{notice}</div>}
 </main>;

 const sellerItem=product.source==='seller';
 return <main className="fitroom-app in-store-app">
  <header className="app-header"><Link className="brand" href="/" aria-label="FITROOM 역할 선택으로 이동"><span className="brand-mark"><ScanLine size={23}/></span>fitroom<span className="brand-period">.</span></Link><div className="header-center"><span className="nav-active">가상 매장 체험</span><span className="header-divider"/>{activeStore}</div><Link className="body-button" href="/seller"><Sparkles size={16}/> 판매자 센터</Link></header>
  <div className="page-heading store-page-heading"><div><button type="button" className="store-back" onClick={leaveStore}><ArrowLeft/>상점 거리</button><span className="store-route">VIRTUAL STREET <ChevronRight/> <b>{activeStore}</b></span><h1>{activeStore}에 입장했어요.</h1></div><span className="collection-count">IN-STORE ITEMS <b>{String(storeProducts.length).padStart(2,'0')}</b></span></div>
  {activeVirtualStore?.hasLiveSellerItems&&<section className="seller-publication-banner"><span><Store/></span><div><strong>판매자가 직접 문을 연 가상 매장</strong><p>판매자가 등록한 가격·재고·실측과 상점 링크를 확인할 수 있어요.</p></div><a href="/seller/products">판매자 상품 보기 <ArrowUpRight/></a></section>}
  <section className="workspace"><div className="fitting-panel"><AvatarView body={body} outfit={outfit} products={catalog} storeName={activeStore} onDrop={id=>{const found=lookup(id);if(found)equip(found);}}/><div className="look-bar"><div><ShoppingBag/><span>지금 입은 옷</span></div><div>{SLOT_ORDER.map(slot=>{const worn=outfit[slot],item=worn&&lookup(worn.productId);return item?<button type="button" key={slot} onClick={()=>setOutfit(current=>remove(current,slot))} aria-label={`${item.name} 벗기`}><small>{SLOT_LABELS[slot]}</small>{item.name}<X/></button>:<span key={slot}><small>{SLOT_LABELS[slot]}</small>비어 있음</span>;})}</div></div><div className="body-strip"><div className="body-strip-title"><span className="body-dot"/><span>{saved?'저장된 내 체형':'기본 체형'}</span><span className="body-mini">{saved?'피팅 패스 적용 중':'내 치수로 바꿔보세요'}</span></div><div className="body-numbers"><span>키 <b>{body.measurements.height}</b><small>cm</small></span><span>가슴 <b>{body.measurements.chest}</b></span><span>허리 <b>{body.measurements.waist}</b></span><button onClick={()=>setEditor(true)} aria-label="체형 수정"><SlidersHorizontal size={15}/></button></div></div></div>
   <aside className="wardrobe-panel" aria-label={`${activeStore} 매장 옷걸이`}><div className="wardrobe-heading"><div><Shirt size={18}/><h2>매장 옷걸이</h2></div><span>끌어서 피팅룸에 놓기</span></div><nav className="rack-tabs" aria-label="상품 종류 바로가기">{SLOT_ORDER.map(slot=><button type="button" key={slot} className={product.slot===slot?'active':''} onClick={()=>rackRefs.current[slot]?.scrollIntoView({behavior:'smooth',block:'nearest'})}><span>{SLOT_LABELS[slot]}</span><small>{storeProducts.filter(item=>item.slot===slot).length}</small></button>)}</nav>
   {SLOT_ORDER.map((slot,index)=>{
    const items=storeProducts.filter(item=>item.slot===slot);
    return <section className="closet-section" key={slot} ref={element=>{rackRefs.current[slot]=element;}}><div className="section-heading"><h3><span>RACK 0{index+1}</span>{SLOT_LABELS[slot]}<small>{items.length}</small></h3>{items.length>0&&<div className="scroll-buttons"><button aria-label={`${SLOT_LABELS[slot]} 이전 상품`} onClick={()=>rowRefs.current[slot]?.scrollBy({left:-220,behavior:'smooth'})}><ChevronLeft size={15}/></button><button aria-label={`${SLOT_LABELS[slot]} 다음 상품`} onClick={()=>rowRefs.current[slot]?.scrollBy({left:220,behavior:'smooth'})}><ChevronRight size={15}/></button></div>}</div>{items.length===0?<div className="empty-rack">이 상점에는 아직 {SLOT_LABELS[slot]} 상품이 없어요.</div>:<div className="product-row" ref={element=>{rowRefs.current[slot]=element;}}>{items.map(item=>{
     const worn=outfit[slot]?.productId===item.id;
     return <article key={item.id} className={`product-card ${selected===item.id?'selected':''} ${worn?'worn':''} ${item.source==='seller'?'seller-item':''}`} draggable onDragStart={event=>{event.dataTransfer.setData('text/plain',item.id);event.dataTransfer.effectAllowed='copy';}}><button className="product-photo" aria-label={`${item.brand} ${item.name} 상세 보기`} onClick={()=>setSelected(item.id)}><img src={item.image} alt={item.source==='seller'?`${SLOT_LABELS[item.slot]} 기본 3D 참고 이미지`:`${item.name} ${item.colorName}의 참고용 3D 의상`} draggable={false}/>{item.source==='seller'&&<span className="seller-item-badge">판매자 등록</span>}{worn&&<span className="wearing-badge"><Check size={11}/>착용 중</span>}<span className="swatch" style={{background:item.color}}/></button><button className="product-description" onClick={()=>setSelected(item.id)}><span>{item.brand}</span><strong>{item.name}</strong></button><button className={`wear-button ${worn?'is-worn':''}`} onClick={()=>worn?(setOutfit(current=>remove(current,slot)),setNotice(`${SLOT_LABELS[slot]}를 벗었어요.`)):equip(item)} aria-label={`${item.name} ${worn?'벗기':'입어보기'}`}>{worn?<><X size={12}/>벗기</>:<><Plus size={12}/>입어보기</>}</button></article>;
    })}</div>}</section>;
   })}
   <p className="catalog-note"><Info size={13}/> 옷걸이에서 고른 상품은 색상·실루엣을 단순화한 3D 의상으로 표현됩니다.</p></aside>
  </section>
  <section className="selection-panel" aria-label="선택한 상품과 실측 비교"><div className="selected-product"><img src={product.image} alt=""/><div><span className="eyebrow">{sellerItem?'NEW SELLER ITEM':'IN-STORE ITEM'}</span><p className="selected-brand">{product.brand}{sellerItem&&<em>판매자 등록</em>}</p><h2>{product.name}</h2><span className="color-label"><i style={{background:product.color}}/>{product.colorName}</span></div></div><div className="size-section"><div className="label-row"><h3>사이즈 선택</h3><span>{sellerItem?'판매자 입력 실측':'시연용 판매자 실측'}</span></div><div className="size-options" role="group" aria-label="상품 사이즈">{product.sizes.map(item=><button key={item.label} className={size.label===item.label?'active':''} aria-pressed={size.label===item.label} onClick={()=>chooseSize(item.label)}>{item.label}</button>)}</div><button className="text-button" onClick={()=>equip(product,size.label)}><Plus size={13}/> 피팅룸에서 입어보기</button></div><div className="fit-section"><div className="label-row"><h3>예상 핏</h3><span className="estimate-badge">검증 전 추정</span></div><div className="fit-values">{[...fit.filter(item=>item.kind==='difference'),...fit.filter(item=>item.label.endsWith('총장')),...fit.filter(item=>item.kind==='unavailable'),...fit.filter(item=>item.kind==='length'&&!item.label.endsWith('총장'))].slice(0,2).map(item=><div key={item.label}><span>{item.label}</span><strong className={item.value!==null&&item.kind==='difference'&&item.value<0?'negative':''}>{item.value===null?'판단 보류':`${item.kind==='difference'&&item.value>0?'+':''}${item.value}`}<small>{item.unit}</small></strong>{item.source&&<small>{sourceLabel[item.source]}</small>}</div>)}</div></div><div className="seller-purchase"><div><strong>{product.priceKrw?.toLocaleString('ko-KR')}원</strong><span>{product.stock===0?'현재 품절':`재고 ${product.stock}개`}</span></div>{product.url?<a className="purchase-button" href={product.url} target="_blank" rel="noopener noreferrer">상점에서 구매하기<ArrowUpRight size={19}/></a>:<span className="purchase-button is-disabled">{sellerItem?'상점 링크 준비 중':'시연 상품'}</span>}</div></section>
  <details className="measurement-details"><summary><Info size={14}/> 실측 정보와 판단 근거 확인<ChevronRight size={14}/></summary><div className="measurement-content"><div><h3>상품 실측 · cm</h3><div className="measurement-table">{Object.entries(size).filter(([key,value])=>key!=='label'&&value!==undefined).map(([key,value])=><div key={key}><span>{MEASUREMENT_LABELS[key]??key}</span><b>{String(value)}</b></div>)}</div><p>{product.note}</p><span className="seller-measurement-source">실측 출처 · {sellerItem?'판매자 직접 입력':'소상공인 입점 시연 데이터'}</span><small>확인일 {product.checkedAt} · {product.url?'구매와 배송 정보는 해당 상점에서 확인하세요.':'실제 상점 연결 전 시연 상품입니다.'}</small></div><div><h3>계산 방법과 한계</h3>{fit.map(item=><p key={item.label}><b>{item.label}</b> — {item.detail}</p>)}<p>3D는 참고 실루엣입니다. 원단의 늘어남·주름·착용감을 재현하지 않으며 실제 착용 결과로 검증되지 않았어요.</p></div></div></details>
  <footer className="app-footer"><span>FITROOM METAVERSE · {activeStore}에서 피팅 중</span><button type="button" onClick={leaveStore}>다른 상점 둘러보기</button></footer>
  <BodyEditor open={editor} onOpenChange={setEditor} body={body} onSave={saveBody} onDelete={deleteBody}/>{notice&&<div className="toast" role="status"><Check size={16}/>{notice}</div>}
 </main>;
}
