'use client';

import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import Link from 'next/link';
import {ArrowLeft,ArrowUpRight,BookmarkPlus,Check,ChevronLeft,ChevronRight,DoorOpen,Heart,Info,LayoutGrid,MapPin,Music2,Plus,ScanLine,Shirt,ShoppingBag,SlidersHorizontal,Sparkles,Store,X} from 'lucide-react';
import AvatarView from '@/components/avatar-view';
import BodyEditor from '@/components/body-editor';
import WardrobeCollection from '@/components/wardrobe-collection';
import {publishedSellerCatalog} from '@/lib/seller/catalog';
import {parseStoredSellerProducts,SELLER_PRODUCTS_STORAGE_KEY} from '@/lib/seller/products';
import {parseStoredSellerStore,sellerStoreLayout,SELLER_STORE_MUSIC_LABELS,SELLER_STORE_STORAGE_KEY,SELLER_STORE_THEME_ACCENTS,SELLER_STORE_THEME_LABELS,SELLER_STORE_ZONE_LABELS,SELLER_STORE_ZONES,stepSellerStoreZone,type SellerStoreProfile,type SellerStoreZone} from '@/lib/seller/store';
import {DEFAULT_BODY,parseStoredBody,sourceLabel,STORAGE_KEY} from '@/lib/wardrobe/body';
import {PRODUCTS,SLOT_LABELS} from '@/lib/wardrobe/catalog';
import {createWardrobeCollection,parseStoredWardrobeCollection,removeSavedLook,saveWardrobeLook,toggleFavoriteProduct,WARDROBE_COLLECTION_STORAGE_KEY,type SavedLook,type WardrobeCollection as WardrobeCollectionState} from '@/lib/wardrobe/collection';
import {estimateFit,remove,wear} from '@/lib/wardrobe/fit';
import {appendInterestEvent,parseStoredInterestLog,WARDROBE_INTEREST_STORAGE_KEY,type InterestSignalType} from '@/lib/wardrobe/interest';
import {recommendWardrobeProducts} from '@/lib/wardrobe/recommendations';
import {buildVirtualStores} from '@/lib/wardrobe/stores';
import {mergePublicSellerProducts,mergePublicSellerStores,parsePublicSellerCatalogResponse,type PublicSellerStore} from '@/lib/wardrobe/public-catalog';
import type {BodyProfile,Outfit,Product,Slot} from '@/lib/wardrobe/types';
import {useWardrobeTools} from '@/lib/wardrobe/webmcp';

const MEASUREMENT_LABELS:Record<string,string>={length:'총장',chestFlat:'가슴단면',chestCirc:'가슴둘레',shoulder:'어깨너비',sleeve:'소매길이',waistFlat:'허리단면',hipsFlat:'엉덩이단면',thighFlat:'허벅지단면',rise:'밑위',hemFlat:'밑단단면',headCirc:'머리둘레'};
const SLOT_ORDER:Slot[]=['hat','top','bottom'];

export default function Wardrobe(){
 const [body,setBody]=useState(DEFAULT_BODY),[saved,setSaved]=useState(false),[editor,setEditor]=useState(false);
 const [outfit,setOutfit]=useState<Outfit>({top:{productId:'6170660',size:'M'},bottom:{productId:'3504218',size:'30'}});
 const [selected,setSelected]=useState('6170660'),[sizes,setSizes]=useState<Record<string,string>>({}),[notice,setNotice]=useState('');
 const [localSellerProducts,setLocalSellerProducts]=useState<ReturnType<typeof parseStoredSellerProducts>>([]),[localSellerStore,setLocalSellerStore]=useState<SellerStoreProfile|null>(null),[remoteSellerStores,setRemoteSellerStores]=useState<PublicSellerStore[]>([]),[catalogStatus,setCatalogStatus]=useState<'loading'|'ready'|'offline'>('loading'),[activeStore,setActiveStore]=useState<string|null>(null),[enteringStore,setEnteringStore]=useState<string|null>(null),[floorZone,setFloorZone]=useState<SellerStoreZone>('left-wall');
 const [collection,setCollection]=useState<WardrobeCollectionState>(()=>createWardrobeCollection()),[collectionOpen,setCollectionOpen]=useState(false);
 const sellerProfiles=useMemo(()=>mergePublicSellerStores(localSellerStore,remoteSellerStores),[localSellerStore,remoteSellerStores]);
 const sellerProfileByName=useMemo(()=>new Map(sellerProfiles.map(store=>[store.storeName,store])),[sellerProfiles]);
 const sellerProducts=useMemo(()=>publishedSellerCatalog(mergePublicSellerProducts(localSellerProducts,remoteSellerStores)),[localSellerProducts,remoteSellerStores]);
 const catalog=useMemo(()=>[...sellerProducts,...PRODUCTS],[sellerProducts]);
 const stores=useMemo(()=>buildVirtualStores(catalog).map(store=>{const profile=sellerProfileByName.get(store.name);return profile?{...store,accent:SELLER_STORE_THEME_ACCENTS[profile.theme]}:store;}),[catalog,sellerProfileByName]);
 const storeProducts=useMemo(()=>activeStore?catalog.filter(item=>item.brand===activeStore):[],[activeStore,catalog]);
 const activeSellerStore=activeStore?sellerProfileByName.get(activeStore)??null:null;
 const activeSellerLayout=useMemo(()=>activeSellerStore?sellerStoreLayout(activeSellerStore,storeProducts.flatMap(item=>item.source==='seller'&&item.sellerProductId?[item.sellerProductId]:[])):null,[activeSellerStore,storeProducts]);
 const activeVirtualStore=stores.find(store=>store.name===activeStore);
 const product=catalog.find(item=>item.id===selected)??storeProducts[0]??PRODUCTS[0];
 const selectedSize=sizes[product.id]??(outfit[product.slot]?.productId===product.id?outfit[product.slot]?.size:product.defaultSize);
 const size=product.sizes.find(item=>item.label===selectedSize)??product.sizes.find(item=>item.label===product.defaultSize)!;
 const fit=estimateFit(body,product,size),rowRefs=useRef<Partial<Record<Slot,HTMLDivElement|null>>>({}),rackRefs=useRef<Partial<Record<Slot,HTMLElement|null>>>({}),floorZoneRefs=useRef<Partial<Record<SellerStoreZone,HTMLElement|null>>>({}),entryTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const collectionCount=collection.favoriteProductIds.length+collection.looks.length;
 const recommendations=useMemo(()=>recommendWardrobeProducts(catalog,collection,4).flatMap(recommendation=>{const item=catalog.find(candidate=>candidate.id===recommendation.productId);return item?[{...recommendation,product:item}]:[];}),[catalog,collection]);
 const recommendedStoreNames=useMemo(()=>new Set(recommendations.map(item=>item.product.brand)),[recommendations]);

 useEffect(()=>{
  const syncSellerProducts=()=>{try{setLocalSellerProducts(parseStoredSellerProducts(localStorage.getItem(SELLER_PRODUCTS_STORAGE_KEY)));}catch{setLocalSellerProducts([]);}};
  const syncSellerStore=()=>{try{setLocalSellerStore(parseStoredSellerStore(localStorage.getItem(SELLER_STORE_STORAGE_KEY)));}catch{setLocalSellerStore(null);}};
  const syncCollection=()=>{try{setCollection(parseStoredWardrobeCollection(localStorage.getItem(WARDROBE_COLLECTION_STORAGE_KEY)));}catch{setCollection(createWardrobeCollection());}};
  const hydrate=window.setTimeout(()=>{try{const stored=parseStoredBody(localStorage.getItem(STORAGE_KEY));if(stored){setBody(stored);setSaved(true);}}catch{}syncSellerProducts();syncSellerStore();syncCollection();},0);
  const handleStorage=(event:StorageEvent)=>{if(event.key===SELLER_PRODUCTS_STORAGE_KEY)syncSellerProducts();if(event.key===SELLER_STORE_STORAGE_KEY)syncSellerStore();if(event.key===WARDROBE_COLLECTION_STORAGE_KEY)syncCollection();};
  window.addEventListener('storage',handleStorage);return()=>{window.clearTimeout(hydrate);window.removeEventListener('storage',handleStorage);};
 },[]);
 useEffect(()=>{const controller=new AbortController();void fetch('/api/catalog/stores',{cache:'no-store',signal:controller.signal}).then(async response=>{const parsed=parsePublicSellerCatalogResponse(await response.json());if(!response.ok||!parsed)throw new Error('invalid public catalog');setRemoteSellerStores(parsed.stores);setCatalogStatus('ready');}).catch(error=>{if((error as Error).name!=='AbortError')setCatalogStatus('offline');});return()=>controller.abort();},[]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),3200);return()=>clearTimeout(timer);},[notice]);
 useEffect(()=>()=>{if(entryTimer.current)clearTimeout(entryTimer.current);},[]);

 function lookup(id:string){return catalog.find(item=>item.id===id);}
 function enterStore(name:string,initialProductId?:string){const first=catalog.find(item=>item.brand===name),initial=initialProductId?catalog.find(item=>item.id===initialProductId&&item.brand===name):undefined;if(!first||enteringStore)return;const profile=sellerProfileByName.get(name);if(profile)setFloorZone(SELLER_STORE_ZONES.find(zone=>profile.placements.some(item=>item.zone===zone))??'left-wall');setEnteringStore(name);entryTimer.current=setTimeout(()=>{setActiveStore(name);setSelected(initial?.id??first.id);setEnteringStore(null);setNotice(initial?`${initial.name} 추천 상세를 열었어요.`:`${name} 가상 매장에 입장했어요.`);window.scrollTo({top:0,behavior:'smooth'});},620);}
 function leaveStore(){setActiveStore(null);setNotice('상점 거리로 나왔어요. 입어본 옷은 그대로 유지됩니다.');window.scrollTo({top:0,behavior:'smooth'});}
 function recordInterestSignal(type:InterestSignalType,productIds:string[]){try{const current=parseStoredInterestLog(localStorage.getItem(WARDROBE_INTEREST_STORAGE_KEY));const id=typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():`signal-${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem(WARDROBE_INTEREST_STORAGE_KEY,JSON.stringify(appendInterestEvent(current,type,productIds,id)));}catch{}}
 function equip(item:Product,label?:string){const chosen=label??sizes[item.id]??item.defaultSize;setOutfit(current=>wear(current,item,chosen));setSelected(item.id);setSizes(current=>({...current,[item.id]:chosen}));recordInterestSignal('try_on',[item.id]);setNotice(`${item.brand}의 ${item.name}을 입었어요.`);}
 function visitFloorZone(zone:SellerStoreZone){setFloorZone(zone);const sellerId=activeSellerLayout?.[zone][0],first=storeProducts.find(item=>item.source==='seller'&&item.sellerProductId===sellerId);if(first)setSelected(first.id);setNotice(`${SELLER_STORE_ZONE_LABELS[zone]} 진열을 둘러봅니다.`);if(window.matchMedia('(max-width: 900px)').matches)window.setTimeout(()=>floorZoneRefs.current[zone]?.scrollIntoView({behavior:'smooth',block:'center'}),30);}
 function chooseSize(label:string){setSizes(current=>({...current,[product.id]:label}));if(outfit[product.slot]?.productId===product.id)setOutfit(current=>wear(current,product,label));}
 function saveBody(next:BodyProfile){setBody(next);try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));setSaved(true);setNotice('내 체형을 피팅 패스에 저장했어요.');}catch{setSaved(false);setNotice('기기에 저장하지 못했어요. 이번 사용 중에는 적용됩니다.');}setEditor(false);}
 function deleteBody(){try{localStorage.removeItem(STORAGE_KEY);}catch{setNotice('저장된 체형을 삭제하지 못했어요. 브라우저 설정을 확인해 주세요.');return;}setBody(DEFAULT_BODY);setSaved(false);setNotice('저장한 체형을 삭제했어요. 기본 체형으로 돌아갑니다.');setEditor(false);}
 function persistCollection(next:WardrobeCollectionState,message:string){setCollection(next);try{localStorage.setItem(WARDROBE_COLLECTION_STORAGE_KEY,JSON.stringify(next));setNotice(message);}catch{setNotice('보관함을 기기에 저장하지 못했어요. 이번 사용 중에는 유지됩니다.');}}
 function toggleFavorite(id:string){const removing=collection.favoriteProductIds.includes(id);persistCollection(toggleFavoriteProduct(collection,id),removing?'찜에서 삭제했어요.':'찜한 상품에 추가했어요.');if(!removing)recordInterestSignal('favorite_add',[id]);}
 function saveCurrentLook(){const productIds=Object.values(outfit).flatMap(item=>item?[item.productId]:[]);if(productIds.length===0){setNotice('먼저 한 가지 이상의 상품을 입어주세요.');return;}const id=typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():`look-${Date.now()}`;persistCollection(saveWardrobeLook(collection,outfit,id),'현재 코디를 보관함에 저장했어요.');recordInterestSignal('look_save',productIds);}
 function restoreLook(look:SavedLook){const next:Outfit={},restored:Product[]=[];let missing=0;for(const slot of SLOT_ORDER){const worn=look.outfit[slot];if(!worn)continue;const item=lookup(worn.productId);if(!item||item.slot!==slot||!item.sizes.some(candidate=>candidate.label===worn.size)){missing++;continue;}next[slot]=worn;restored.push(item);}if(restored.length===0){setNotice('현재 판매 중인 상품이 없어 이 코디를 불러올 수 없어요.');return;}setOutfit(next);setSizes(current=>({...current,...Object.fromEntries(restored.map(item=>[item.id,next[item.slot]!.size]))}));setSelected(restored[0].id);setActiveStore(restored[0].brand);setCollectionOpen(false);setNotice(missing?'저장한 코디에서 판매 중인 상품만 다시 입었어요.':'저장한 코디를 다시 입었어요.');window.scrollTo({top:0,behavior:'smooth'});}
 function openCollectedProduct(id:string){const item=lookup(id);if(!item){toggleFavorite(id);return;}setCollectionOpen(false);if(!activeStore){enterStore(item.brand,item.id);return;}setActiveStore(item.brand);setSelected(item.id);setNotice(`${item.name} 상세를 열었어요.`);window.scrollTo({top:0,behavior:'smooth'});}
 function openRecommendation(item:Product){recordInterestSignal('recommendation_open',[item.id]);enterStore(item.brand,item.id);}

 useWardrobeTools({body,outfit},items=>{
  setOutfit(previous=>items.reduce((current,item)=>{const found=lookup(item.productId);return found?wear(current,found,item.size):current;},previous));
  setSizes(previous=>({...previous,...Object.fromEntries(items.map(item=>[item.productId,item.size]))}));
  setSelected(items[items.length-1].productId);setNotice('선택한 옷을 입었어요.');
 });

 if(!activeStore)return <main className="fitroom-app market-app">
  <header className="app-header"><Link className="brand" href="/" aria-label="FITROOM 역할 선택으로 이동"><span className="brand-mark"><ScanLine size={23}/></span>fitroom<span className="brand-period">.</span></Link><div className="header-center"><span className="nav-active">가상 상점 거리</span><span className="header-divider"/>소상공인 패션 월드</div><div className="shopper-header-actions"><button type="button" className="collection-button" onClick={()=>setCollectionOpen(true)}><Heart/>보관함<small>{collectionCount}</small></button><Link className="body-button" href="/seller"><Sparkles size={16}/> 판매자 센터</Link></div></header>
  <section className="market-hero"><div className="market-vista" aria-hidden="true"><span className="vista-building vista-left"><i/><i/><i/></span><span className="vista-building vista-right"><i/><i/><i/></span><span className="vista-gate">fitroom.<small>VIRTUAL FASHION STREET</small></span><span className="vista-path"/></div><div className="market-copy"><span className="eyebrow">VIRTUAL FASHION STREET</span><h1>어느 옷가게에<br/>들어가 볼까요?</h1><p>상점 문을 열고 들어가 옷걸이에서 상품을 고른 뒤,<br/>내 체형의 아바타에게 바로 입혀보세요.</p><div className="market-status"><span><MapPin/>가상 상점 {stores.length}곳</span><span><Shirt/>입어볼 옷 {catalog.length}벌</span></div></div><aside className="fit-pass"><div><span>MY FIT PASS</span><strong>{body.measurements.height}<small>cm</small></strong><p>{saved?'저장된 내 체형으로 입장합니다.':'기본 체형으로 둘러볼 수 있어요.'}</p></div><dl><div><dt>가슴</dt><dd>{body.measurements.chest}</dd></div><div><dt>허리</dt><dd>{body.measurements.waist}</dd></div><div><dt>엉덩이</dt><dd>{body.measurements.hips}</dd></div></dl><button type="button" onClick={()=>setEditor(true)}><SlidersHorizontal/>체형 설정</button></aside></section>
  <section className={`recommendation-section ${recommendations.length===0?'is-empty':''}`} aria-labelledby="recommendation-title"><div className="recommendation-heading"><div><span className="eyebrow"><Sparkles/> FOR YOU</span><h2 id="recommendation-title">내 보관함으로 골랐어요</h2><p>찜한 상품과 저장 코디의 상점·종류·색상·실루엣을 이 브라우저 안에서만 비교합니다.</p></div><span className="local-recommendation"><Check/>기기 안에서 추천</span></div>{recommendations.length===0?<div className="recommendation-empty"><Heart/><div><strong>취향을 조금만 알려주세요</strong><p>상품을 찜하거나 코디를 저장하면 이곳에서 내 취향과 닮은 상품을 추천해요.</p></div></div>:<div className="recommendation-grid">{recommendations.map(({product:item,reasons})=>{const favorite=collection.favoriteProductIds.includes(item.id);return <article className="recommendation-card" key={item.id}><button type="button" className="recommendation-main" onClick={()=>openRecommendation(item)} disabled={Boolean(enteringStore)} aria-label={`${item.brand} ${item.name} 추천 상품 보기`}><span className="recommendation-image"><img src={item.image} alt=""/><i style={{background:item.color}}/></span><span className="recommendation-copy"><small>{item.brand} · {SLOT_LABELS[item.slot]}</small><strong>{item.name}</strong><em>{item.priceKrw===undefined?'가격 정보 준비 중':`${item.priceKrw.toLocaleString('ko-KR')}원`}</em><span className="recommendation-reasons">{reasons.map(reason=><b key={reason}>{reason}</b>)}</span><span className="recommendation-enter">매장에서 보기 <ArrowUpRight/></span></span></button><button type="button" className={`recommendation-favorite ${favorite?'active':''}`} onClick={()=>toggleFavorite(item.id)} aria-label={`${item.name} ${favorite?'찜 해제':'찜하기'}`}><Heart fill={favorite?'currentColor':'none'}/></button></article>;})}</div>}</section>
  <section className="store-street" aria-labelledby="store-street-title"><div className="street-heading"><div><span className="eyebrow">SHOP STREET</span><h2 id="store-street-title">오늘 문을 연 상점</h2></div><span aria-live="polite">{catalogStatus==='loading'?'입점 매장 동기화 중':catalogStatus==='offline'?'서버 연결 없이 기본 매장 표시 중':`${sellerProfiles.length}개 판매자 매장 연결`}</span></div><div className="storefront-grid">{stores.map((store,index)=>{const customStore=sellerProfileByName.get(store.name),recommended=recommendedStoreNames.has(store.name);return <button type="button" className={`storefront-card ${customStore?'custom-store':''} ${recommended?'recommended-store':''}`} key={store.name} onClick={()=>enterStore(store.name)} disabled={Boolean(enteringStore)} style={{'--store-accent':store.accent} as CSSProperties} aria-label={`${store.name} 가상 매장 입장`}><div className="storefront-top"><span>{String(index+1).padStart(2,'0')}</span>{store.hasLiveSellerItems&&<em>{customStore?'CUSTOM STORE':'NEW SELLER'}</em>}<b>OPEN</b></div><div className="storefront-visual"><div className="storefront-sign"><strong>{store.name}</strong><small>{customStore?'SELLER CUSTOM STORE':'FITROOM SELECT SHOP'}</small></div><div className="storefront-window">{store.products.slice(0,3).map((item,itemIndex)=><span key={item.id} style={{zIndex:3-itemIndex}}><img src={item.image} alt=""/></span>)}</div><span className="storefront-door"><DoorOpen/><small>ENTER</small></span></div><div className="storefront-info">{recommended&&<span className="store-match"><Sparkles/>내 취향 추천</span>}<small>{store.slots.map(slot=>SLOT_LABELS[slot]).join(' · ')}</small><h3>{store.name}</h3><p>{customStore?customStore.tagline:`${store.products.length}개의 상품을 입어볼 수 있어요.`}</p><span className="enter-store">매장 입장 <DoorOpen/></span></div></button>;})}</div></section>
  <footer className="app-footer"><span>FITROOM METAVERSE · 작은 상점의 옷을 내 체형으로.</span><span>가상 매장과 상품은 실제 판매자 게시 정보에 따라 확장됩니다.</span></footer>
  <WardrobeCollection open={collectionOpen} collection={collection} products={catalog} onClose={()=>setCollectionOpen(false)} onSelectProduct={openCollectedProduct} onToggleFavorite={toggleFavorite} onRestoreLook={restoreLook} onRemoveLook={id=>persistCollection(removeSavedLook(collection,id),'저장한 코디를 삭제했어요.')}/><BodyEditor open={editor} onOpenChange={setEditor} body={body} onSave={saveBody} onDelete={deleteBody}/>{enteringStore&&<div className="store-entry-transition" role="status" aria-live="polite"><div><span>ENTERING STORE</span><DoorOpen/><strong>{enteringStore}</strong><small>가상 매장으로 들어가는 중</small></div></div>}{notice&&<div className="toast" role="status"><Check size={16}/>{notice}</div>}
 </main>;

 const sellerItem=product.source==='seller';
 return <main className="fitroom-app in-store-app">
  <header className="app-header"><Link className="brand" href="/" aria-label="FITROOM 역할 선택으로 이동"><span className="brand-mark"><ScanLine size={23}/></span>fitroom<span className="brand-period">.</span></Link><div className="header-center"><span className="nav-active">가상 매장 체험</span><span className="header-divider"/>{activeStore}</div><div className="shopper-header-actions"><button type="button" className="collection-button" onClick={()=>setCollectionOpen(true)}><Heart/>보관함<small>{collectionCount}</small></button><Link className="body-button" href="/seller"><Sparkles size={16}/> 판매자 센터</Link></div></header>
  <div className="page-heading store-page-heading"><div><button type="button" className="store-back" onClick={leaveStore}><ArrowLeft/>상점 거리</button><span className="store-route">VIRTUAL STREET <ChevronRight/> <b>{activeStore}</b></span><h1>{activeStore}에 입장했어요.</h1></div><span className="collection-count">IN-STORE ITEMS <b>{String(storeProducts.length).padStart(2,'0')}</b></span></div>
  {activeVirtualStore?.hasLiveSellerItems&&<section className="seller-publication-banner"><span><Store/></span><div><strong>판매자가 직접 문을 연 가상 매장</strong><p>판매자가 등록한 가격·재고·실측과 상점 링크를 확인할 수 있어요.</p></div><a href="/seller/products">판매자 상품 보기 <ArrowUpRight/></a></section>}
  {activeSellerLayout&&activeSellerStore&&<section className={`shop-floor-plan theme-${activeSellerStore.theme}`} style={{'--store-accent':SELLER_STORE_THEME_ACCENTS[activeSellerStore.theme]} as CSSProperties} aria-labelledby="shop-floor-title"><header><div><span className="eyebrow">SELLER CURATED FLOOR</span><h2 id="shop-floor-title"><LayoutGrid/>판매자가 꾸민 매장 진열</h2><p>{activeSellerStore.tagline}</p></div><div className="shop-floor-meta"><span><i/>{SELLER_STORE_THEME_LABELS[activeSellerStore.theme]}</span><span><Music2/>{SELLER_STORE_MUSIC_LABELS[activeSellerStore.music]}</span></div></header><nav className="shop-floor-tour-bar" aria-label="매장 진열 구역 이동"><button type="button" onClick={()=>visitFloorZone(stepSellerStoreZone(floorZone,-1))} aria-label="이전 진열 구역"><ChevronLeft/></button><div><small>매장 동선 {SELLER_STORE_ZONES.indexOf(floorZone)+1} / {SELLER_STORE_ZONES.length}</small><strong>{SELLER_STORE_ZONE_LABELS[floorZone]}</strong><span>{SELLER_STORE_ZONES.map((zone,index)=><button type="button" key={zone} className={floorZone===zone?'active':''} aria-label={`${index+1}번 구역 이동: ${SELLER_STORE_ZONE_LABELS[zone]}`} aria-pressed={floorZone===zone} onClick={()=>visitFloorZone(zone)}/>)}</span></div><button type="button" onClick={()=>visitFloorZone(stepSellerStoreZone(floorZone,1))} aria-label="다음 진열 구역"><ChevronRight/></button></nav><div className={`shop-floor-room view-${floorZone}`}><div className="shop-floor-sign"><strong>{activeSellerStore.storeName}</strong><small>상품을 선택하거나 바로 입어보세요</small></div>{SELLER_STORE_ZONES.map(zone=>{const items=activeSellerLayout[zone].map(id=>storeProducts.find(item=>item.source==='seller'&&item.sellerProductId===id)).filter((item):item is Product=>Boolean(item));return <section key={zone} ref={element=>{floorZoneRefs.current[zone]=element;}} className={`shop-floor-zone floor-zone-${zone} ${floorZone===zone?'active':''}`} aria-label={SELLER_STORE_ZONE_LABELS[zone]}><button type="button" className="shop-floor-zone-title" onClick={()=>visitFloorZone(zone)} aria-pressed={floorZone===zone}><span>{SELLER_STORE_ZONE_LABELS[zone]}</span><small>{items.length}</small></button><div>{items.length===0?<span className="shop-floor-empty">비어 있는 진열 구역</span>:items.map(item=><article key={item.id} className={selected===item.id?'selected':''}><button type="button" className="shop-floor-item" onClick={()=>{setFloorZone(zone);setSelected(item.id);setNotice(`${SELLER_STORE_ZONE_LABELS[zone]}의 ${item.name}을 선택했어요.`);}}><img src={item.image} alt=""/><span><small>{SLOT_LABELS[item.slot]}</small><strong>{item.name}</strong></span></button><button type="button" className="shop-floor-wear" onClick={()=>{setFloorZone(zone);equip(item);}} aria-label={`${item.name} 바로 입어보기`}><Plus/><span>입어보기</span></button></article>)}</div></section>;})}<div className="shop-floor-counter"/><div className="shop-floor-lines"/></div></section>}
  <section className="workspace"><div className="fitting-panel"><AvatarView body={body} outfit={outfit} products={catalog} storeName={activeStore} onDrop={id=>{const found=lookup(id);if(found)equip(found);}}/><div className="look-bar"><div><ShoppingBag/><span>지금 입은 옷</span></div><div>{SLOT_ORDER.map(slot=>{const worn=outfit[slot],item=worn&&lookup(worn.productId);return item?<button type="button" key={slot} onClick={()=>setOutfit(current=>remove(current,slot))} aria-label={`${item.name} 벗기`}><small>{SLOT_LABELS[slot]}</small>{item.name}<X/></button>:<span key={slot}><small>{SLOT_LABELS[slot]}</small>비어 있음</span>;})}</div></div><div className="look-save-strip"><div><BookmarkPlus/><span><strong>현재 코디 보관</strong><small>{Object.values(outfit).filter(Boolean).length}개 상품을 다시 입을 수 있게 저장해요.</small></span></div><button type="button" onClick={saveCurrentLook}>코디 저장</button></div><div className="body-strip"><div className="body-strip-title"><span className="body-dot"/><span>{saved?'저장된 내 체형':'기본 체형'}</span><span className="body-mini">{saved?'피팅 패스 적용 중':'내 치수로 바꿔보세요'}</span></div><div className="body-numbers"><span>키 <b>{body.measurements.height}</b><small>cm</small></span><span>가슴 <b>{body.measurements.chest}</b></span><span>허리 <b>{body.measurements.waist}</b></span><button onClick={()=>setEditor(true)} aria-label="체형 수정"><SlidersHorizontal size={15}/></button></div></div></div>
   <aside className="wardrobe-panel" aria-label={`${activeStore} 매장 옷걸이`}><div className="wardrobe-heading"><div><Shirt size={18}/><h2>매장 옷걸이</h2></div><span>끌어서 피팅룸에 놓기</span></div><nav className="rack-tabs" aria-label="상품 종류 바로가기">{SLOT_ORDER.map(slot=><button type="button" key={slot} className={product.slot===slot?'active':''} onClick={()=>rackRefs.current[slot]?.scrollIntoView({behavior:'smooth',block:'nearest'})}><span>{SLOT_LABELS[slot]}</span><small>{storeProducts.filter(item=>item.slot===slot).length}</small></button>)}</nav>
   {SLOT_ORDER.map((slot,index)=>{
    const items=storeProducts.filter(item=>item.slot===slot);
    return <section className="closet-section" key={slot} ref={element=>{rackRefs.current[slot]=element;}}><div className="section-heading"><h3><span>RACK 0{index+1}</span>{SLOT_LABELS[slot]}<small>{items.length}</small></h3>{items.length>0&&<div className="scroll-buttons"><button aria-label={`${SLOT_LABELS[slot]} 이전 상품`} onClick={()=>rowRefs.current[slot]?.scrollBy({left:-220,behavior:'smooth'})}><ChevronLeft size={15}/></button><button aria-label={`${SLOT_LABELS[slot]} 다음 상품`} onClick={()=>rowRefs.current[slot]?.scrollBy({left:220,behavior:'smooth'})}><ChevronRight size={15}/></button></div>}</div>{items.length===0?<div className="empty-rack">이 상점에는 아직 {SLOT_LABELS[slot]} 상품이 없어요.</div>:<div className="product-row" ref={element=>{rowRefs.current[slot]=element;}}>{items.map(item=>{
     const worn=outfit[slot]?.productId===item.id;
     const favorite=collection.favoriteProductIds.includes(item.id);
     return <article key={item.id} className={`product-card ${selected===item.id?'selected':''} ${worn?'worn':''} ${item.source==='seller'?'seller-item':''}`} draggable onDragStart={event=>{event.dataTransfer.setData('text/plain',item.id);event.dataTransfer.effectAllowed='copy';}}><button className="product-photo" aria-label={`${item.brand} ${item.name} 상세 보기`} onClick={()=>setSelected(item.id)}><img src={item.image} alt={item.source==='seller'?`${SLOT_LABELS[item.slot]} 기본 3D 참고 이미지`:`${item.name} ${item.colorName}의 참고용 3D 의상`} draggable={false}/>{item.source==='seller'&&<span className="seller-item-badge">판매자 등록</span>}{worn&&<span className="wearing-badge"><Check size={11}/>착용 중</span>}<span className="swatch" style={{background:item.color}}/></button><button type="button" className={`product-favorite ${favorite?'active':''}`} onClick={()=>toggleFavorite(item.id)} aria-label={`${item.name} ${favorite?'찜 해제':'찜하기'}`}><Heart fill={favorite?'currentColor':'none'}/></button><button className="product-description" onClick={()=>setSelected(item.id)}><span>{item.brand}</span><strong>{item.name}</strong></button><button className={`wear-button ${worn?'is-worn':''}`} onClick={()=>worn?(setOutfit(current=>remove(current,slot)),setNotice(`${SLOT_LABELS[slot]}를 벗었어요.`)):equip(item)} aria-label={`${item.name} ${worn?'벗기':'입어보기'}`}>{worn?<><X size={12}/>벗기</>:<><Plus size={12}/>입어보기</>}</button></article>;
    })}</div>}</section>;
   })}
   <p className="catalog-note"><Info size={13}/> 옷걸이에서 고른 상품은 색상·실루엣을 단순화한 3D 의상으로 표현됩니다.</p></aside>
  </section>
  <section className="selection-panel" aria-label="선택한 상품과 실측 비교"><div className="selected-product"><img src={product.image} alt=""/><div><span className="eyebrow">{sellerItem?'NEW SELLER ITEM':'IN-STORE ITEM'}</span><p className="selected-brand">{product.brand}{sellerItem&&<em>판매자 등록</em>}</p><h2>{product.name}</h2><span className="color-label"><i style={{background:product.color}}/>{product.colorName}</span></div><button type="button" className={`selected-favorite ${collection.favoriteProductIds.includes(product.id)?'active':''}`} onClick={()=>toggleFavorite(product.id)} aria-label={`${product.name} ${collection.favoriteProductIds.includes(product.id)?'찜 해제':'찜하기'}`}><Heart fill={collection.favoriteProductIds.includes(product.id)?'currentColor':'none'}/><span>{collection.favoriteProductIds.includes(product.id)?'찜함':'찜하기'}</span></button></div><div className="size-section"><div className="label-row"><h3>사이즈 선택</h3><span>{sellerItem?'판매자 입력 실측':'시연용 판매자 실측'}</span></div><div className="size-options" role="group" aria-label="상품 사이즈">{product.sizes.map(item=><button key={item.label} className={size.label===item.label?'active':''} aria-pressed={size.label===item.label} onClick={()=>chooseSize(item.label)}>{item.label}</button>)}</div><button className="text-button" onClick={()=>equip(product,size.label)}><Plus size={13}/> 피팅룸에서 입어보기</button></div><div className="fit-section"><div className="label-row"><h3>예상 핏</h3><span className="estimate-badge">검증 전 추정</span></div><div className="fit-values">{[...fit.filter(item=>item.kind==='difference'),...fit.filter(item=>item.label.endsWith('총장')),...fit.filter(item=>item.kind==='unavailable'),...fit.filter(item=>item.kind==='length'&&!item.label.endsWith('총장'))].slice(0,2).map(item=><div key={item.label}><span>{item.label}</span><strong className={item.value!==null&&item.kind==='difference'&&item.value<0?'negative':''}>{item.value===null?'판단 보류':`${item.kind==='difference'&&item.value>0?'+':''}${item.value}`}<small>{item.unit}</small></strong>{item.source&&<small>{sourceLabel[item.source]}</small>}</div>)}</div></div><div className="seller-purchase"><div><strong>{product.priceKrw?.toLocaleString('ko-KR')}원</strong><span>{product.stock===0?'현재 품절':`재고 ${product.stock}개`}</span></div>{product.url?<a className="purchase-button" href={product.url} target="_blank" rel="noopener noreferrer">상점에서 구매하기<ArrowUpRight size={19}/></a>:<span className="purchase-button is-disabled">{sellerItem?'상점 링크 준비 중':'시연 상품'}</span>}</div></section>
  <details className="measurement-details"><summary><Info size={14}/> 실측 정보와 판단 근거 확인<ChevronRight size={14}/></summary><div className="measurement-content"><div><h3>상품 실측 · cm</h3><div className="measurement-table">{Object.entries(size).filter(([key,value])=>key!=='label'&&value!==undefined).map(([key,value])=><div key={key}><span>{MEASUREMENT_LABELS[key]??key}</span><b>{String(value)}</b></div>)}</div><p>{product.note}</p><span className="seller-measurement-source">실측 출처 · {sellerItem?'판매자 직접 입력':'소상공인 입점 시연 데이터'}</span><small>확인일 {product.checkedAt} · {product.url?'구매와 배송 정보는 해당 상점에서 확인하세요.':'실제 상점 연결 전 시연 상품입니다.'}</small></div><div><h3>계산 방법과 한계</h3>{fit.map(item=><p key={item.label}><b>{item.label}</b> — {item.detail}</p>)}<p>3D는 참고 실루엣입니다. 원단의 늘어남·주름·착용감을 재현하지 않으며 실제 착용 결과로 검증되지 않았어요.</p></div></div></details>
  <footer className="app-footer"><span>FITROOM METAVERSE · {activeStore}에서 피팅 중</span><button type="button" onClick={leaveStore}>다른 상점 둘러보기</button></footer>
  <WardrobeCollection open={collectionOpen} collection={collection} products={catalog} onClose={()=>setCollectionOpen(false)} onSelectProduct={openCollectedProduct} onToggleFavorite={toggleFavorite} onRestoreLook={restoreLook} onRemoveLook={id=>persistCollection(removeSavedLook(collection,id),'저장한 코디를 삭제했어요.')}/><BodyEditor open={editor} onOpenChange={setEditor} body={body} onSave={saveBody} onDelete={deleteBody}/>{notice&&<div className="toast" role="status"><Check size={16}/>{notice}</div>}
 </main>;
}
